DROP TABLE IF EXISTS document_indexes CASCADE;
DROP TABLE IF EXISTS document_attributes CASCADE;
DROP TABLE IF EXISTS document_collections CASCADE;
DROP TABLE IF EXISTS document_databases CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
