// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx/boot"
	"github.com/torchwooddev/torchwood/internal/app/assets"
	billing2 "github.com/torchwooddev/torchwood/internal/app/billing"
	functions2 "github.com/torchwooddev/torchwood/internal/app/functions"
	payments2 "github.com/torchwooddev/torchwood/internal/app/payments"
	storage2 "github.com/torchwooddev/torchwood/internal/app/storage"
	"github.com/torchwooddev/torchwood/internal/app/subscriptions"
	"github.com/torchwooddev/torchwood/internal/infra/billing"
	"github.com/torchwooddev/torchwood/internal/infra/bun/bunrepo"
	"github.com/torchwooddev/torchwood/internal/infra/clients"
	"github.com/torchwooddev/torchwood/internal/infra/events"
	"github.com/torchwooddev/torchwood/internal/infra/functions"
	"github.com/torchwooddev/torchwood/internal/infra/payments"
	"github.com/torchwooddev/torchwood/internal/infra/queue"
	"github.com/torchwooddev/torchwood/internal/infra/realtime"
	"github.com/torchwooddev/torchwood/internal/infra/storage"
	"github.com/torchwooddev/torchwood/internal/pkg/bootkit"
)

// Injectors from wire.go:

func wireBootstrap(app lynx.App) (*boot.Bootstrap, func(), error) {
	appConfig, err := NewAppConfig(app)
	if err != nil {
		return nil, nil, err
	}
	logger := bootkit.NewLogger(app)
	dataClients, cleanup, err := clients.NewDataClients(appConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	database := clients.NewDatabase(dataClients)
	repository := bunrepo.NewProjectRepository(database)
	v := NewGrantsReconcileHook()
	onStartHooks := bootkit.NewOnStarts(repository, database, logger, v)
	onStopHooks := bootkit.NewOnStops()
	executor := functions.NewDockerExecutor(appConfig)
	functionRepo := bunrepo.NewFunctionRepository(database)
	client := clients.NewRedis(dataClients)
	sharedQueue := queue.NewRedisQueue(client)
	redisCounter := billing.NewRedisCounter(client)
	semaphores := functions2.ProvideSemaphores(client, appConfig)
	functionsFunctions := functions2.NewFunctionsWithUsage(appConfig, executor, functionRepo, sharedQueue, redisCounter, repository, semaphores)
	worker := NewWorker(functionsFunctions, sharedQueue, logger)
	objectStore, err := storage.NewMinioObjectStore(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	uploadSessionStore := storage.NewRedisUploadSessionStore(client)
	bucketRepository := bunrepo.NewBucketRepository(database)
	fileRepository := bunrepo.NewFileRepository(database)
	v2 := NewStorageOptions()
	storageStorage := storage2.NewStorage(appConfig, repository, objectStore, uploadSessionStore, bucketRepository, fileRepository, v2...)
	mainChunkCleaner := NewChunkCleaner(storageStorage, logger)
	streamTrimmer := NewStreamTrimmer(sharedQueue, logger)
	realtimeTransport := realtime.NewStreamTransport(client)
	outboxWorker := events.NewOutboxWorker(database, realtimeTransport, logger)
	outboxWorkerService := NewOutboxWorkerService(outboxWorker, logger)
	orderRepo := bunrepo.NewPaymentOrderRepository(database)
	callbackEventRepo := bunrepo.NewPaymentCallbackEventRepository(database)
	fulfillmentRepo := bunrepo.NewPaymentFulfillmentRepository(database)
	defRepo := bunrepo.NewAssetDefRepository(database)
	holdingRepo := bunrepo.NewAssetHoldingRepository(database)
	ledgerRepo := bunrepo.NewAssetLedgerRepository(database)
	eventOutbox := events.NewEventOutbox(database)
	assetsAssets := assets.NewAssets(database, defRepo, holdingRepo, ledgerRepo, eventOutbox, logger, repository)
	planRepo := bunrepo.NewSubscriptionPlanRepository(database)
	subscriptionRepo := bunrepo.NewSubscriptionRepository(database)
	adapter := payments.NewStripeAdapter(appConfig)
	wechatAdapter := payments.NewWeChatAdapter(appConfig)
	alipayAdapter := payments.NewAlipayAdapter(appConfig)
	iosiapAdapter := payments.NewIosIapAdapter(appConfig)
	registry := payments.ProvideRegistry(adapter, wechatAdapter, alipayAdapter, iosiapAdapter)
	providerIndexRepo := bunrepo.NewProviderIndexRepository(database)
	subscriptionsSubscriptions := subscriptions.NewSubscriptions(appConfig, database, planRepo, subscriptionRepo, assetsAssets, orderRepo, registry, adapter, eventOutbox, logger, repository, providerIndexRepo)
	fulfiller := subscriptions.NewOrderFulfiller(assetsAssets, subscriptionsSubscriptions)
	paymentsPayments := payments2.NewPayments(appConfig, database, orderRepo, callbackEventRepo, fulfillmentRepo, fulfiller, registry, eventOutbox, logger, subscriptionsSubscriptions, repository, providerIndexRepo)
	paymentCloser := NewPaymentCloser(paymentsPayments, logger)
	assetExpirer := NewAssetExpirer(assetsAssets, logger)
	subscriptionBiller := NewSubscriptionBiller(subscriptionsSubscriptions, logger)
	usageRepo := bunrepo.NewUsageRepository(database)
	statementRepo := bunrepo.NewBillingStatementRepository(database)
	billingBilling := billing2.NewBilling(redisCounter, usageRepo, statementRepo, repository, fileRepository, logger)
	usageRollupWorker := NewUsageRollupWorker(billingBilling, logger)
	v3 := NewComponents(worker, mainChunkCleaner, streamTrimmer, outboxWorkerService, paymentCloser, assetExpirer, subscriptionBiller, usageRollupWorker)
	v4 := bootkit.NewComponentBuilders()
	bootstrap := boot.New(onStartHooks, onStopHooks, v3, v4)
	return bootstrap, func() {
		cleanup()
	}, nil
}
