// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: server/v1/billing.proto

package serverv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/torchwooddev/torchwood/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetUsageRequest 查询时间窗内的用量合计；未设 period 时默认当前 UTC 月。
type GetUsageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 空=全部计量点（api_calls / storage_bytes / function_duration_ms）。
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageRequest) Reset() {
	*x = GetUsageRequest{}
	mi := &file_server_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageRequest) ProtoMessage() {}

func (x *GetUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageRequest.ProtoReflect.Descriptor instead.
func (*GetUsageRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsageRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *GetUsageRequest) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *GetUsageRequest) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

// Usage 是项目在时间窗内各 metric 的合计（value 一律 int64 最小单位）。
type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	Metrics       []*UsageMetric         `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_server_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_server_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *Usage) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Usage) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *Usage) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *Usage) GetMetrics() []*UsageMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type UsageMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageMetric) Reset() {
	*x = UsageMetric{}
	mi := &file_server_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageMetric) ProtoMessage() {}

func (x *UsageMetric) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageMetric.ProtoReflect.Descriptor instead.
func (*UsageMetric) Descriptor() ([]byte, []int) {
	return file_server_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *UsageMetric) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *UsageMetric) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// ListRollupsRequest 列出小时 rollup（period_start DESC）。
type ListRollupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Metric        string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRollupsRequest) Reset() {
	*x = ListRollupsRequest{}
	mi := &file_server_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRollupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRollupsRequest) ProtoMessage() {}

func (x *ListRollupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRollupsRequest.ProtoReflect.Descriptor instead.
func (*ListRollupsRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *ListRollupsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRollupsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRollupsRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *ListRollupsRequest) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *ListRollupsRequest) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

// UsageRollup 是一小时 bucket 的落表行。
type UsageRollup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Metric        string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	Value         int64                  `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageRollup) Reset() {
	*x = UsageRollup{}
	mi := &file_server_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageRollup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageRollup) ProtoMessage() {}

func (x *UsageRollup) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageRollup.ProtoReflect.Descriptor instead.
func (*UsageRollup) Descriptor() ([]byte, []int) {
	return file_server_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *UsageRollup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UsageRollup) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UsageRollup) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *UsageRollup) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *UsageRollup) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ListRollupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rollups       []*UsageRollup         `protobuf:"bytes,1,rep,name=rollups,proto3" json:"rollups,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRollupsResponse) Reset() {
	*x = ListRollupsResponse{}
	mi := &file_server_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRollupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRollupsResponse) ProtoMessage() {}

func (x *ListRollupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRollupsResponse.ProtoReflect.Descriptor instead.
func (*ListRollupsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *ListRollupsResponse) GetRollups() []*UsageRollup {
	if x != nil {
		return x.Rollups
	}
	return nil
}

func (x *ListRollupsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// BillingStatement 是月账单文档（draft → final；JSONB 明细与 rollups 对账）。
type BillingStatement struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId   string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PeriodStart *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	// draft | final
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FinalizedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finalized_at,json=finalizedAt,proto3" json:"finalized_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingStatement) Reset() {
	*x = BillingStatement{}
	mi := &file_server_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingStatement) ProtoMessage() {}

func (x *BillingStatement) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingStatement.ProtoReflect.Descriptor instead.
func (*BillingStatement) Descriptor() ([]byte, []int) {
	return file_server_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *BillingStatement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BillingStatement) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *BillingStatement) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *BillingStatement) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *BillingStatement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BillingStatement) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *BillingStatement) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BillingStatement) GetFinalizedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinalizedAt
	}
	return nil
}

type ListStatementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statements    []*BillingStatement    `protobuf:"bytes,1,rep,name=statements,proto3" json:"statements,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStatementsResponse) Reset() {
	*x = ListStatementsResponse{}
	mi := &file_server_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatementsResponse) ProtoMessage() {}

func (x *ListStatementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatementsResponse.ProtoReflect.Descriptor instead.
func (*ListStatementsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *ListStatementsResponse) GetStatements() []*BillingStatement {
	if x != nil {
		return x.Statements
	}
	return nil
}

func (x *ListStatementsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_server_v1_billing_proto protoreflect.FileDescriptor

const file_server_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x17server/v1/billing.proto\x12\x13torchwood.server.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x15shared/v1/authz.proto\x1a\x16shared/v1/common.proto\"\xa3\x01\n" +
	"\x0fGetUsageRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12=\n" +
	"\fperiod_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\"\xdc\x01\n" +
	"\x05Usage\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12=\n" +
	"\fperiod_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12:\n" +
	"\ametrics\x18\x04 \x03(\v2 .torchwood.server.v1.UsageMetricR\ametrics\";\n" +
	"\vUsageMetric\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"\xe2\x01\n" +
	"\x12ListRollupsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12=\n" +
	"\fperiod_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\"\xa9\x01\n" +
	"\vUsageRollup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12=\n" +
	"\fperiod_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x03R\x05value\"\x8c\x01\n" +
	"\x13ListRollupsResponse\x12:\n" +
	"\arollups\x18\x01 \x03(\v2 .torchwood.server.v1.UsageRollupR\arollups\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta\"\x80\x03\n" +
	"\x10BillingStatement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12=\n" +
	"\fperiod_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x121\n" +
	"\adetails\x18\x06 \x01(\v2\x17.google.protobuf.StructR\adetails\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\ffinalized_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vfinalizedAt\"\x9a\x01\n" +
	"\x16ListStatementsResponse\x12E\n" +
	"\n" +
	"statements\x18\x01 \x03(\v2%.torchwood.server.v1.BillingStatementR\n" +
	"statements\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta2\x98\x03\n" +
	"\x0eBillingService\x12n\n" +
	"\bGetUsage\x12$.torchwood.server.v1.GetUsageRequest\x1a\x1a.torchwood.server.v1.Usage\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/server/billing/usage\x12\x84\x01\n" +
	"\vListRollups\x12'.torchwood.server.v1.ListRollupsRequest\x1a(.torchwood.server.v1.ListRollupsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/server/billing/rollups\x12\x86\x01\n" +
	"\x0eListStatements\x12 .torchwood.shared.v1.ListRequest\x1a+.torchwood.server.v1.ListStatementsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/server/billing/statements\x1a\x06\x92\xb2\x19\x02\b\x04B\x86\x03\x92A\xc3\x02Z\x91\x02\n" +
	"3\n" +
	"\x06Bearer\x12)\b\x02\x12\x14格式: Bearer <jwt>\x1a\rAuthorization \x02\n" +
	"\x86\x01\n" +
	"\x06apiKey\x12|\b\x02\x12k项目绑定在密钥行上，不需要 X-Torchwood-Project。该头仅 Console admin 会话切换项目。\x1a\tX-API-Key \x02\n" +
	"Q\n" +
	"\x06cookie\x12G\b\x02\x129TORCHWOOD_session_console=<sid>（Console admin 会话）\x1a\x06Cookie \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06apiKey\x12\x00z\x1f\n" +
	"\x12x-torchwood-access\x12\t\x1a\aapi_keyZ=github.com/torchwooddev/torchwood/genproto/server/v1;serverv1b\x06proto3"

var (
	file_server_v1_billing_proto_rawDescOnce sync.Once
	file_server_v1_billing_proto_rawDescData []byte
)

func file_server_v1_billing_proto_rawDescGZIP() []byte {
	file_server_v1_billing_proto_rawDescOnce.Do(func() {
		file_server_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_billing_proto_rawDesc), len(file_server_v1_billing_proto_rawDesc)))
	})
	return file_server_v1_billing_proto_rawDescData
}

var file_server_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_server_v1_billing_proto_goTypes = []any{
	(*GetUsageRequest)(nil),        // 0: torchwood.server.v1.GetUsageRequest
	(*Usage)(nil),                  // 1: torchwood.server.v1.Usage
	(*UsageMetric)(nil),            // 2: torchwood.server.v1.UsageMetric
	(*ListRollupsRequest)(nil),     // 3: torchwood.server.v1.ListRollupsRequest
	(*UsageRollup)(nil),            // 4: torchwood.server.v1.UsageRollup
	(*ListRollupsResponse)(nil),    // 5: torchwood.server.v1.ListRollupsResponse
	(*BillingStatement)(nil),       // 6: torchwood.server.v1.BillingStatement
	(*ListStatementsResponse)(nil), // 7: torchwood.server.v1.ListStatementsResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*v1.ListResponseMeta)(nil),    // 9: torchwood.shared.v1.ListResponseMeta
	(*structpb.Struct)(nil),        // 10: google.protobuf.Struct
	(*v1.ListRequest)(nil),         // 11: torchwood.shared.v1.ListRequest
}
var file_server_v1_billing_proto_depIdxs = []int32{
	8,  // 0: torchwood.server.v1.GetUsageRequest.period_start:type_name -> google.protobuf.Timestamp
	8,  // 1: torchwood.server.v1.GetUsageRequest.period_end:type_name -> google.protobuf.Timestamp
	8,  // 2: torchwood.server.v1.Usage.period_start:type_name -> google.protobuf.Timestamp
	8,  // 3: torchwood.server.v1.Usage.period_end:type_name -> google.protobuf.Timestamp
	2,  // 4: torchwood.server.v1.Usage.metrics:type_name -> torchwood.server.v1.UsageMetric
	8,  // 5: torchwood.server.v1.ListRollupsRequest.period_start:type_name -> google.protobuf.Timestamp
	8,  // 6: torchwood.server.v1.ListRollupsRequest.period_end:type_name -> google.protobuf.Timestamp
	8,  // 7: torchwood.server.v1.UsageRollup.period_start:type_name -> google.protobuf.Timestamp
	4,  // 8: torchwood.server.v1.ListRollupsResponse.rollups:type_name -> torchwood.server.v1.UsageRollup
	9,  // 9: torchwood.server.v1.ListRollupsResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	8,  // 10: torchwood.server.v1.BillingStatement.period_start:type_name -> google.protobuf.Timestamp
	8,  // 11: torchwood.server.v1.BillingStatement.period_end:type_name -> google.protobuf.Timestamp
	10, // 12: torchwood.server.v1.BillingStatement.details:type_name -> google.protobuf.Struct
	8,  // 13: torchwood.server.v1.BillingStatement.created_at:type_name -> google.protobuf.Timestamp
	8,  // 14: torchwood.server.v1.BillingStatement.finalized_at:type_name -> google.protobuf.Timestamp
	6,  // 15: torchwood.server.v1.ListStatementsResponse.statements:type_name -> torchwood.server.v1.BillingStatement
	9,  // 16: torchwood.server.v1.ListStatementsResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	0,  // 17: torchwood.server.v1.BillingService.GetUsage:input_type -> torchwood.server.v1.GetUsageRequest
	3,  // 18: torchwood.server.v1.BillingService.ListRollups:input_type -> torchwood.server.v1.ListRollupsRequest
	11, // 19: torchwood.server.v1.BillingService.ListStatements:input_type -> torchwood.shared.v1.ListRequest
	1,  // 20: torchwood.server.v1.BillingService.GetUsage:output_type -> torchwood.server.v1.Usage
	5,  // 21: torchwood.server.v1.BillingService.ListRollups:output_type -> torchwood.server.v1.ListRollupsResponse
	7,  // 22: torchwood.server.v1.BillingService.ListStatements:output_type -> torchwood.server.v1.ListStatementsResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_server_v1_billing_proto_init() }
func file_server_v1_billing_proto_init() {
	if File_server_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_billing_proto_rawDesc), len(file_server_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_billing_proto_goTypes,
		DependencyIndexes: file_server_v1_billing_proto_depIdxs,
		MessageInfos:      file_server_v1_billing_proto_msgTypes,
	}.Build()
	File_server_v1_billing_proto = out.File
	file_server_v1_billing_proto_goTypes = nil
	file_server_v1_billing_proto_depIdxs = nil
}
