// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: server/v1/billing.proto

package serverv1

import (
	context "context"
	v1 "github.com/torchwooddev/torchwood/genproto/shared/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_GetUsage_FullMethodName       = "/torchwood.server.v1.BillingService/GetUsage"
	BillingService_ListRollups_FullMethodName    = "/torchwood.server.v1.BillingService/ListRollups"
	BillingService_ListStatements_FullMethodName = "/torchwood.server.v1.BillingService/ListStatements"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BillingService 是平台用量查询面（v3 设计 §4 / §6）：当前用量、小时
// rollup、月账单文档。全部只读；scope billing.read / console admin。
// 一期不出票、不向 owner 收款、不挂钩配额/限流。
type BillingServiceClient interface {
	GetUsage(ctx context.Context, in *GetUsageRequest, opts ...grpc.CallOption) (*Usage, error)
	ListRollups(ctx context.Context, in *ListRollupsRequest, opts ...grpc.CallOption) (*ListRollupsResponse, error)
	ListStatements(ctx context.Context, in *v1.ListRequest, opts ...grpc.CallOption) (*ListStatementsResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) GetUsage(ctx context.Context, in *GetUsageRequest, opts ...grpc.CallOption) (*Usage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Usage)
	err := c.cc.Invoke(ctx, BillingService_GetUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListRollups(ctx context.Context, in *ListRollupsRequest, opts ...grpc.CallOption) (*ListRollupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRollupsResponse)
	err := c.cc.Invoke(ctx, BillingService_ListRollups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListStatements(ctx context.Context, in *v1.ListRequest, opts ...grpc.CallOption) (*ListStatementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStatementsResponse)
	err := c.cc.Invoke(ctx, BillingService_ListStatements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
//
// BillingService 是平台用量查询面（v3 设计 §4 / §6）：当前用量、小时
// rollup、月账单文档。全部只读；scope billing.read / console admin。
// 一期不出票、不向 owner 收款、不挂钩配额/限流。
type BillingServiceServer interface {
	GetUsage(context.Context, *GetUsageRequest) (*Usage, error)
	ListRollups(context.Context, *ListRollupsRequest) (*ListRollupsResponse, error)
	ListStatements(context.Context, *v1.ListRequest) (*ListStatementsResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) GetUsage(context.Context, *GetUsageRequest) (*Usage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsage not implemented")
}
func (UnimplementedBillingServiceServer) ListRollups(context.Context, *ListRollupsRequest) (*ListRollupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRollups not implemented")
}
func (UnimplementedBillingServiceServer) ListStatements(context.Context, *v1.ListRequest) (*ListStatementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStatements not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_GetUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetUsage(ctx, req.(*GetUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListRollups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRollupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListRollups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListRollups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListRollups(ctx, req.(*ListRollupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListStatements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListStatements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListStatements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListStatements(ctx, req.(*v1.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "torchwood.server.v1.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsage",
			Handler:    _BillingService_GetUsage_Handler,
		},
		{
			MethodName: "ListRollups",
			Handler:    _BillingService_ListRollups_Handler,
		},
		{
			MethodName: "ListStatements",
			Handler:    _BillingService_ListStatements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/v1/billing.proto",
}
