// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: server/v1/functions.proto

package serverv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/torchwooddev/torchwood/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Function struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Runtime        string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Entrypoint     string                 `protobuf:"bytes,5,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Spec           string                 `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	Enabled        bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_server_v1_functions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{0}
}

func (x *Function) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Function) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Function) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *Function) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Function) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *Function) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Function) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Function) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RuntimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Entrypoint    string                 `protobuf:"bytes,3,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_server_v1_functions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuntimeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeInfo) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

type SpecificationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cpu           string                 `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecificationInfo) Reset() {
	*x = SpecificationInfo{}
	mi := &file_server_v1_functions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecificationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecificationInfo) ProtoMessage() {}

func (x *SpecificationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecificationInfo.ProtoReflect.Descriptor instead.
func (*SpecificationInfo) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{2}
}

func (x *SpecificationInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpecificationInfo) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *SpecificationInfo) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FunctionId    string                 `protobuf:"bytes,2,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_server_v1_functions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{3}
}

func (x *Deployment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Deployment) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *Deployment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Deployment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Deployment) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Deployment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Deployment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Variables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variables     []*Variable            `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variables) Reset() {
	*x = Variables{}
	mi := &file_server_v1_functions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variables) ProtoMessage() {}

func (x *Variables) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variables.ProtoReflect.Descriptor instead.
func (*Variables) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{4}
}

func (x *Variables) GetVariables() []*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type Variable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 环境变量值：SetVariables 请求透传明文；GetVariables 与 SetVariables
	// 响应统一返回掩码（"******"），真实值仅在 SetVariables 请求中可见一次
	// （对齐 internal/app/functions/variables.go 的 secretMask 约定）。
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_server_v1_functions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{5}
}

func (x *Variable) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Variable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Execution struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FunctionId        string                 `protobuf:"bytes,2,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	DeploymentId      string                 `protobuf:"bytes,3,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Response          string                 `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	Stdout            string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr            string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	StatusCode        int32                  `protobuf:"varint,8,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	DurationMs        int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error             string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	ResponseTruncated bool                   `protobuf:"varint,11,opt,name=response_truncated,json=responseTruncated,proto3" json:"response_truncated,omitempty"`
	StdoutTruncated   bool                   `protobuf:"varint,12,opt,name=stdout_truncated,json=stdoutTruncated,proto3" json:"stdout_truncated,omitempty"`
	StderrTruncated   bool                   `protobuf:"varint,13,opt,name=stderr_truncated,json=stderrTruncated,proto3" json:"stderr_truncated,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Execution) Reset() {
	*x = Execution{}
	mi := &file_server_v1_functions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execution) ProtoMessage() {}

func (x *Execution) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execution.ProtoReflect.Descriptor instead.
func (*Execution) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{6}
}

func (x *Execution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Execution) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *Execution) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *Execution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Execution) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *Execution) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *Execution) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *Execution) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Execution) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Execution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Execution) GetResponseTruncated() bool {
	if x != nil {
		return x.ResponseTruncated
	}
	return false
}

func (x *Execution) GetStdoutTruncated() bool {
	if x != nil {
		return x.StdoutTruncated
	}
	return false
}

func (x *Execution) GetStderrTruncated() bool {
	if x != nil {
		return x.StderrTruncated
	}
	return false
}

func (x *Execution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Execution) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateFunctionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端自选 function_id；functions:runtimes / functions:specifications
	// 为自定义方法段（REST 自定义动词），不再占用 function_id 命名空间，
	// 可自由取任意合法值。
	Id             string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Runtime        string  `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Entrypoint     string  `protobuf:"bytes,4,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	TimeoutSeconds *int32  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3,oneof" json:"timeout_seconds,omitempty"`
	Spec           *string `protobuf:"bytes,6,opt,name=spec,proto3,oneof" json:"spec,omitempty"`
	Enabled        *bool   `protobuf:"varint,7,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateFunctionRequest) Reset() {
	*x = CreateFunctionRequest{}
	mi := &file_server_v1_functions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionRequest) ProtoMessage() {}

func (x *CreateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionRequest.ProtoReflect.Descriptor instead.
func (*CreateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{7}
}

func (x *CreateFunctionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFunctionRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *CreateFunctionRequest) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *CreateFunctionRequest) GetTimeoutSeconds() int32 {
	if x != nil && x.TimeoutSeconds != nil {
		return *x.TimeoutSeconds
	}
	return 0
}

func (x *CreateFunctionRequest) GetSpec() string {
	if x != nil && x.Spec != nil {
		return *x.Spec
	}
	return ""
}

func (x *CreateFunctionRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type UpdateFunctionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FunctionId     string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	Name           *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Entrypoint     *string                `protobuf:"bytes,3,opt,name=entrypoint,proto3,oneof" json:"entrypoint,omitempty"`
	TimeoutSeconds *int32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3,oneof" json:"timeout_seconds,omitempty"`
	Spec           *string                `protobuf:"bytes,5,opt,name=spec,proto3,oneof" json:"spec,omitempty"`
	Enabled        *bool                  `protobuf:"varint,6,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateFunctionRequest) Reset() {
	*x = UpdateFunctionRequest{}
	mi := &file_server_v1_functions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFunctionRequest) ProtoMessage() {}

func (x *UpdateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFunctionRequest.ProtoReflect.Descriptor instead.
func (*UpdateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFunctionRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *UpdateFunctionRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateFunctionRequest) GetEntrypoint() string {
	if x != nil && x.Entrypoint != nil {
		return *x.Entrypoint
	}
	return ""
}

func (x *UpdateFunctionRequest) GetTimeoutSeconds() int32 {
	if x != nil && x.TimeoutSeconds != nil {
		return *x.TimeoutSeconds
	}
	return 0
}

func (x *UpdateFunctionRequest) GetSpec() string {
	if x != nil && x.Spec != nil {
		return *x.Spec
	}
	return ""
}

func (x *UpdateFunctionRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type GetFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionRequest) Reset() {
	*x = GetFunctionRequest{}
	mi := &file_server_v1_functions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionRequest) ProtoMessage() {}

func (x *GetFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionRequest.ProtoReflect.Descriptor instead.
func (*GetFunctionRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{9}
}

func (x *GetFunctionRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

// code 为 zip 代码包，≤1MiB 走此通道；更大的包走 multipart 上传
// （POST /v1/server/functions/{function_id}/deployments/code）。
type CreateDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	Code          []byte                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeploymentRequest) Reset() {
	*x = CreateDeploymentRequest{}
	mi := &file_server_v1_functions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeploymentRequest) ProtoMessage() {}

func (x *CreateDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeploymentRequest.ProtoReflect.Descriptor instead.
func (*CreateDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{10}
}

func (x *CreateDeploymentRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *CreateDeploymentRequest) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

type GetDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentRequest) Reset() {
	*x = GetDeploymentRequest{}
	mi := &file_server_v1_functions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentRequest) ProtoMessage() {}

func (x *GetDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{11}
}

func (x *GetDeploymentRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *GetDeploymentRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type CreateExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	DeploymentId  *string                `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3,oneof" json:"deployment_id,omitempty"` // 缺省用最新 ready deployment
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Async         *bool                  `protobuf:"varint,4,opt,name=async,proto3,oneof" json:"async,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExecutionRequest) Reset() {
	*x = CreateExecutionRequest{}
	mi := &file_server_v1_functions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecutionRequest) ProtoMessage() {}

func (x *CreateExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecutionRequest.ProtoReflect.Descriptor instead.
func (*CreateExecutionRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{12}
}

func (x *CreateExecutionRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *CreateExecutionRequest) GetDeploymentId() string {
	if x != nil && x.DeploymentId != nil {
		return *x.DeploymentId
	}
	return ""
}

func (x *CreateExecutionRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *CreateExecutionRequest) GetAsync() bool {
	if x != nil && x.Async != nil {
		return *x.Async
	}
	return false
}

type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_server_v1_functions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{13}
}

func (x *GetExecutionRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *GetExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

// SetVariablesRequest 全量替换函数环境变量。
type SetVariablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	Variables     []*Variable            `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVariablesRequest) Reset() {
	*x = SetVariablesRequest{}
	mi := &file_server_v1_functions_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVariablesRequest) ProtoMessage() {}

func (x *SetVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVariablesRequest.ProtoReflect.Descriptor instead.
func (*SetVariablesRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{14}
}

func (x *SetVariablesRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *SetVariablesRequest) GetVariables() []*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type ListRuntimesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtimes      []*RuntimeInfo         `protobuf:"bytes,1,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimesResponse) Reset() {
	*x = ListRuntimesResponse{}
	mi := &file_server_v1_functions_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimesResponse) ProtoMessage() {}

func (x *ListRuntimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimesResponse.ProtoReflect.Descriptor instead.
func (*ListRuntimesResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{15}
}

func (x *ListRuntimesResponse) GetRuntimes() []*RuntimeInfo {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

type ListSpecificationsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Specifications []*SpecificationInfo   `protobuf:"bytes,1,rep,name=specifications,proto3" json:"specifications,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSpecificationsResponse) Reset() {
	*x = ListSpecificationsResponse{}
	mi := &file_server_v1_functions_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpecificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpecificationsResponse) ProtoMessage() {}

func (x *ListSpecificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpecificationsResponse.ProtoReflect.Descriptor instead.
func (*ListSpecificationsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{16}
}

func (x *ListSpecificationsResponse) GetSpecifications() []*SpecificationInfo {
	if x != nil {
		return x.Specifications
	}
	return nil
}

type ListFunctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []*Function            `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsResponse) Reset() {
	*x = ListFunctionsResponse{}
	mi := &file_server_v1_functions_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsResponse) ProtoMessage() {}

func (x *ListFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{17}
}

func (x *ListFunctionsResponse) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *ListFunctionsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// MVP 不分页。
type ListDeploymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsResponse) Reset() {
	*x = ListDeploymentsResponse{}
	mi := &file_server_v1_functions_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsResponse) ProtoMessage() {}

func (x *ListDeploymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsResponse.ProtoReflect.Descriptor instead.
func (*ListDeploymentsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{18}
}

func (x *ListDeploymentsResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

// MVP 不分页（返回最近 100 条）。
type ListExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*Execution           `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsResponse) Reset() {
	*x = ListExecutionsResponse{}
	mi := &file_server_v1_functions_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsResponse) ProtoMessage() {}

func (x *ListExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_functions_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_functions_proto_rawDescGZIP(), []int{19}
}

func (x *ListExecutionsResponse) GetExecutions() []*Execution {
	if x != nil {
		return x.Executions
	}
	return nil
}

var File_server_v1_functions_proto protoreflect.FileDescriptor

const file_server_v1_functions_proto_rawDesc = "" +
	"\n" +
	"\x19server/v1/functions.proto\x12\x13torchwood.server.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x15shared/v1/authz.proto\x1a\x16shared/v1/common.proto\"\xd4\x02\n" +
	"\bFunction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x05 \x01(\tR\n" +
	"entrypoint\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x12\x12\n" +
	"\x04spec\x18\a \x01(\tR\x04spec\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Q\n" +
	"\vRuntimeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x03 \x01(\tR\n" +
	"entrypoint\"M\n" +
	"\x11SpecificationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\tR\x06memory\"\xf5\x01\n" +
	"\n" +
	"Deployment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vfunction_id\x18\x02 \x01(\tR\n" +
	"functionId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"H\n" +
	"\tVariables\x12;\n" +
	"\tvariables\x18\x01 \x03(\v2\x1d.torchwood.server.v1.VariableR\tvariables\"2\n" +
	"\bVariable\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x98\x04\n" +
	"\tExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vfunction_id\x18\x02 \x01(\tR\n" +
	"functionId\x12#\n" +
	"\rdeployment_id\x18\x03 \x01(\tR\fdeploymentId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bresponse\x18\x05 \x01(\tR\bresponse\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x12\x1f\n" +
	"\vstatus_code\x18\b \x01(\x05R\n" +
	"statusCode\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12-\n" +
	"\x12response_truncated\x18\v \x01(\bR\x11responseTruncated\x12)\n" +
	"\x10stdout_truncated\x18\f \x01(\bR\x0fstdoutTruncated\x12)\n" +
	"\x10stderr_truncated\x18\r \x01(\bR\x0fstderrTruncated\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x84\x02\n" +
	"\x15CreateFunctionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x04 \x01(\tR\n" +
	"entrypoint\x12,\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05H\x00R\x0etimeoutSeconds\x88\x01\x01\x12\x17\n" +
	"\x04spec\x18\x06 \x01(\tH\x01R\x04spec\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\a \x01(\bH\x02R\aenabled\x88\x01\x01B\x12\n" +
	"\x10_timeout_secondsB\a\n" +
	"\x05_specB\n" +
	"\n" +
	"\b_enabled\"\x9d\x02\n" +
	"\x15UpdateFunctionRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12#\n" +
	"\n" +
	"entrypoint\x18\x03 \x01(\tH\x01R\n" +
	"entrypoint\x88\x01\x01\x12,\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05H\x02R\x0etimeoutSeconds\x88\x01\x01\x12\x17\n" +
	"\x04spec\x18\x05 \x01(\tH\x03R\x04spec\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x06 \x01(\bH\x04R\aenabled\x88\x01\x01B\a\n" +
	"\x05_nameB\r\n" +
	"\v_entrypointB\x12\n" +
	"\x10_timeout_secondsB\a\n" +
	"\x05_specB\n" +
	"\n" +
	"\b_enabled\"5\n" +
	"\x12GetFunctionRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\"N\n" +
	"\x17CreateDeploymentRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\fR\x04code\"\\\n" +
	"\x14GetDeploymentRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\"\xae\x01\n" +
	"\x16CreateExecutionRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12(\n" +
	"\rdeployment_id\x18\x02 \x01(\tH\x00R\fdeploymentId\x88\x01\x01\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x19\n" +
	"\x05async\x18\x04 \x01(\bH\x01R\x05async\x88\x01\x01B\x10\n" +
	"\x0e_deployment_idB\b\n" +
	"\x06_async\"Y\n" +
	"\x13GetExecutionRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\"s\n" +
	"\x13SetVariablesRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12;\n" +
	"\tvariables\x18\x02 \x03(\v2\x1d.torchwood.server.v1.VariableR\tvariables\"T\n" +
	"\x14ListRuntimesResponse\x12<\n" +
	"\bruntimes\x18\x01 \x03(\v2 .torchwood.server.v1.RuntimeInfoR\bruntimes\"l\n" +
	"\x1aListSpecificationsResponse\x12N\n" +
	"\x0especifications\x18\x01 \x03(\v2&.torchwood.server.v1.SpecificationInfoR\x0especifications\"\x8f\x01\n" +
	"\x15ListFunctionsResponse\x12;\n" +
	"\tfunctions\x18\x01 \x03(\v2\x1d.torchwood.server.v1.FunctionR\tfunctions\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta\"\\\n" +
	"\x17ListDeploymentsResponse\x12A\n" +
	"\vdeployments\x18\x01 \x03(\v2\x1f.torchwood.server.v1.DeploymentR\vdeployments\"X\n" +
	"\x16ListExecutionsResponse\x12>\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x1e.torchwood.server.v1.ExecutionR\n" +
	"executions2\xd1\x12\n" +
	"\x10FunctionsService\x12|\n" +
	"\fListRuntimes\x12\x1a.torchwood.shared.v1.Empty\x1a).torchwood.server.v1.ListRuntimesResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/server/functions:runtimes\x12\x8e\x01\n" +
	"\x12ListSpecifications\x12\x1a.torchwood.shared.v1.Empty\x1a/.torchwood.server.v1.ListSpecificationsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/server/functions:specifications\x12|\n" +
	"\x0eCreateFunction\x12*.torchwood.server.v1.CreateFunctionRequest\x1a\x1d.torchwood.server.v1.Function\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/server/functions\x12{\n" +
	"\rListFunctions\x12 .torchwood.shared.v1.ListRequest\x1a*.torchwood.server.v1.ListFunctionsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/server/functions\x12\x81\x01\n" +
	"\vGetFunction\x12'.torchwood.server.v1.GetFunctionRequest\x1a\x1d.torchwood.server.v1.Function\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/server/functions/{function_id}\x12\x8a\x01\n" +
	"\x0eUpdateFunction\x12*.torchwood.server.v1.UpdateFunctionRequest\x1a\x1d.torchwood.server.v1.Function\"-\x82\xd3\xe4\x93\x02':\x01*2\"/v1/server/functions/{function_id}\x12\x81\x01\n" +
	"\x0eDeleteFunction\x12'.torchwood.server.v1.GetFunctionRequest\x1a\x1a.torchwood.shared.v1.Empty\"*\x82\xd3\xe4\x93\x02$*\"/v1/server/functions/{function_id}\x12\x9c\x01\n" +
	"\x10CreateDeployment\x12,.torchwood.server.v1.CreateDeploymentRequest\x1a\x1f.torchwood.server.v1.Deployment\"9\x82\xd3\xe4\x93\x023:\x01*\"./v1/server/functions/{function_id}/deployments\x12\xa0\x01\n" +
	"\x0fListDeployments\x12'.torchwood.server.v1.GetFunctionRequest\x1a,.torchwood.server.v1.ListDeploymentsResponse\"6\x82\xd3\xe4\x93\x020\x12./v1/server/functions/{function_id}/deployments\x12\xa3\x01\n" +
	"\rGetDeployment\x12).torchwood.server.v1.GetDeploymentRequest\x1a\x1f.torchwood.server.v1.Deployment\"F\x82\xd3\xe4\x93\x02@\x12>/v1/server/functions/{function_id}/deployments/{deployment_id}\x12\xa1\x01\n" +
	"\x10DeleteDeployment\x12).torchwood.server.v1.GetDeploymentRequest\x1a\x1a.torchwood.shared.v1.Empty\"F\x82\xd3\xe4\x93\x02@*>/v1/server/functions/{function_id}/deployments/{deployment_id}\x12\x97\x01\n" +
	"\fSetVariables\x12(.torchwood.server.v1.SetVariablesRequest\x1a\x1e.torchwood.server.v1.Variables\"=\x8a\xb2\x19\x02\b\x04\x82\xd3\xe4\x93\x021:\x01*\x1a,/v1/server/functions/{function_id}/variables\x12\x93\x01\n" +
	"\fGetVariables\x12'.torchwood.server.v1.GetFunctionRequest\x1a\x1e.torchwood.server.v1.Variables\":\x8a\xb2\x19\x02\b\x04\x82\xd3\xe4\x93\x02.\x12,/v1/server/functions/{function_id}/variables\x12\x98\x01\n" +
	"\x0fCreateExecution\x12+.torchwood.server.v1.CreateExecutionRequest\x1a\x1e.torchwood.server.v1.Execution\"8\x82\xd3\xe4\x93\x022:\x01*\"-/v1/server/functions/{function_id}/executions\x12\x9d\x01\n" +
	"\x0eListExecutions\x12'.torchwood.server.v1.GetFunctionRequest\x1a+.torchwood.server.v1.ListExecutionsResponse\"5\x82\xd3\xe4\x93\x02/\x12-/v1/server/functions/{function_id}/executions\x12\x9e\x01\n" +
	"\fGetExecution\x12(.torchwood.server.v1.GetExecutionRequest\x1a\x1e.torchwood.server.v1.Execution\"D\x82\xd3\xe4\x93\x02>\x12</v1/server/functions/{function_id}/executions/{execution_id}\x1a\x06\x92\xb2\x19\x02\b\x04B\xdb\x02\x92A\x98\x02Z\xe6\x01\n" +
	"3\n" +
	"\x06Bearer\x12)\b\x02\x12\x14格式: Bearer <jwt>\x1a\rAuthorization \x02\n" +
	"\\\n" +
	"\x06apiKey\x12R\b\x02\x12AServer API key（需同时携带 X-Torchwood-Project 请求头）\x1a\tX-API-Key \x02\n" +
	"Q\n" +
	"\x06cookie\x12G\b\x02\x129TORCHWOOD_session_console=<sid>（Console admin 会话）\x1a\x06Cookie \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06apiKey\x12\x00z\x1f\n" +
	"\x12x-torchwood-access\x12\t\x1a\aapi_keyZ=github.com/torchwooddev/torchwood/genproto/server/v1;serverv1b\x06proto3"

var (
	file_server_v1_functions_proto_rawDescOnce sync.Once
	file_server_v1_functions_proto_rawDescData []byte
)

func file_server_v1_functions_proto_rawDescGZIP() []byte {
	file_server_v1_functions_proto_rawDescOnce.Do(func() {
		file_server_v1_functions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_functions_proto_rawDesc), len(file_server_v1_functions_proto_rawDesc)))
	})
	return file_server_v1_functions_proto_rawDescData
}

var file_server_v1_functions_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_server_v1_functions_proto_goTypes = []any{
	(*Function)(nil),                   // 0: torchwood.server.v1.Function
	(*RuntimeInfo)(nil),                // 1: torchwood.server.v1.RuntimeInfo
	(*SpecificationInfo)(nil),          // 2: torchwood.server.v1.SpecificationInfo
	(*Deployment)(nil),                 // 3: torchwood.server.v1.Deployment
	(*Variables)(nil),                  // 4: torchwood.server.v1.Variables
	(*Variable)(nil),                   // 5: torchwood.server.v1.Variable
	(*Execution)(nil),                  // 6: torchwood.server.v1.Execution
	(*CreateFunctionRequest)(nil),      // 7: torchwood.server.v1.CreateFunctionRequest
	(*UpdateFunctionRequest)(nil),      // 8: torchwood.server.v1.UpdateFunctionRequest
	(*GetFunctionRequest)(nil),         // 9: torchwood.server.v1.GetFunctionRequest
	(*CreateDeploymentRequest)(nil),    // 10: torchwood.server.v1.CreateDeploymentRequest
	(*GetDeploymentRequest)(nil),       // 11: torchwood.server.v1.GetDeploymentRequest
	(*CreateExecutionRequest)(nil),     // 12: torchwood.server.v1.CreateExecutionRequest
	(*GetExecutionRequest)(nil),        // 13: torchwood.server.v1.GetExecutionRequest
	(*SetVariablesRequest)(nil),        // 14: torchwood.server.v1.SetVariablesRequest
	(*ListRuntimesResponse)(nil),       // 15: torchwood.server.v1.ListRuntimesResponse
	(*ListSpecificationsResponse)(nil), // 16: torchwood.server.v1.ListSpecificationsResponse
	(*ListFunctionsResponse)(nil),      // 17: torchwood.server.v1.ListFunctionsResponse
	(*ListDeploymentsResponse)(nil),    // 18: torchwood.server.v1.ListDeploymentsResponse
	(*ListExecutionsResponse)(nil),     // 19: torchwood.server.v1.ListExecutionsResponse
	(*timestamppb.Timestamp)(nil),      // 20: google.protobuf.Timestamp
	(*v1.ListResponseMeta)(nil),        // 21: torchwood.shared.v1.ListResponseMeta
	(*v1.Empty)(nil),                   // 22: torchwood.shared.v1.Empty
	(*v1.ListRequest)(nil),             // 23: torchwood.shared.v1.ListRequest
}
var file_server_v1_functions_proto_depIdxs = []int32{
	20, // 0: torchwood.server.v1.Function.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: torchwood.server.v1.Function.updated_at:type_name -> google.protobuf.Timestamp
	20, // 2: torchwood.server.v1.Deployment.created_at:type_name -> google.protobuf.Timestamp
	20, // 3: torchwood.server.v1.Deployment.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 4: torchwood.server.v1.Variables.variables:type_name -> torchwood.server.v1.Variable
	20, // 5: torchwood.server.v1.Execution.created_at:type_name -> google.protobuf.Timestamp
	20, // 6: torchwood.server.v1.Execution.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 7: torchwood.server.v1.SetVariablesRequest.variables:type_name -> torchwood.server.v1.Variable
	1,  // 8: torchwood.server.v1.ListRuntimesResponse.runtimes:type_name -> torchwood.server.v1.RuntimeInfo
	2,  // 9: torchwood.server.v1.ListSpecificationsResponse.specifications:type_name -> torchwood.server.v1.SpecificationInfo
	0,  // 10: torchwood.server.v1.ListFunctionsResponse.functions:type_name -> torchwood.server.v1.Function
	21, // 11: torchwood.server.v1.ListFunctionsResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	3,  // 12: torchwood.server.v1.ListDeploymentsResponse.deployments:type_name -> torchwood.server.v1.Deployment
	6,  // 13: torchwood.server.v1.ListExecutionsResponse.executions:type_name -> torchwood.server.v1.Execution
	22, // 14: torchwood.server.v1.FunctionsService.ListRuntimes:input_type -> torchwood.shared.v1.Empty
	22, // 15: torchwood.server.v1.FunctionsService.ListSpecifications:input_type -> torchwood.shared.v1.Empty
	7,  // 16: torchwood.server.v1.FunctionsService.CreateFunction:input_type -> torchwood.server.v1.CreateFunctionRequest
	23, // 17: torchwood.server.v1.FunctionsService.ListFunctions:input_type -> torchwood.shared.v1.ListRequest
	9,  // 18: torchwood.server.v1.FunctionsService.GetFunction:input_type -> torchwood.server.v1.GetFunctionRequest
	8,  // 19: torchwood.server.v1.FunctionsService.UpdateFunction:input_type -> torchwood.server.v1.UpdateFunctionRequest
	9,  // 20: torchwood.server.v1.FunctionsService.DeleteFunction:input_type -> torchwood.server.v1.GetFunctionRequest
	10, // 21: torchwood.server.v1.FunctionsService.CreateDeployment:input_type -> torchwood.server.v1.CreateDeploymentRequest
	9,  // 22: torchwood.server.v1.FunctionsService.ListDeployments:input_type -> torchwood.server.v1.GetFunctionRequest
	11, // 23: torchwood.server.v1.FunctionsService.GetDeployment:input_type -> torchwood.server.v1.GetDeploymentRequest
	11, // 24: torchwood.server.v1.FunctionsService.DeleteDeployment:input_type -> torchwood.server.v1.GetDeploymentRequest
	14, // 25: torchwood.server.v1.FunctionsService.SetVariables:input_type -> torchwood.server.v1.SetVariablesRequest
	9,  // 26: torchwood.server.v1.FunctionsService.GetVariables:input_type -> torchwood.server.v1.GetFunctionRequest
	12, // 27: torchwood.server.v1.FunctionsService.CreateExecution:input_type -> torchwood.server.v1.CreateExecutionRequest
	9,  // 28: torchwood.server.v1.FunctionsService.ListExecutions:input_type -> torchwood.server.v1.GetFunctionRequest
	13, // 29: torchwood.server.v1.FunctionsService.GetExecution:input_type -> torchwood.server.v1.GetExecutionRequest
	15, // 30: torchwood.server.v1.FunctionsService.ListRuntimes:output_type -> torchwood.server.v1.ListRuntimesResponse
	16, // 31: torchwood.server.v1.FunctionsService.ListSpecifications:output_type -> torchwood.server.v1.ListSpecificationsResponse
	0,  // 32: torchwood.server.v1.FunctionsService.CreateFunction:output_type -> torchwood.server.v1.Function
	17, // 33: torchwood.server.v1.FunctionsService.ListFunctions:output_type -> torchwood.server.v1.ListFunctionsResponse
	0,  // 34: torchwood.server.v1.FunctionsService.GetFunction:output_type -> torchwood.server.v1.Function
	0,  // 35: torchwood.server.v1.FunctionsService.UpdateFunction:output_type -> torchwood.server.v1.Function
	22, // 36: torchwood.server.v1.FunctionsService.DeleteFunction:output_type -> torchwood.shared.v1.Empty
	3,  // 37: torchwood.server.v1.FunctionsService.CreateDeployment:output_type -> torchwood.server.v1.Deployment
	18, // 38: torchwood.server.v1.FunctionsService.ListDeployments:output_type -> torchwood.server.v1.ListDeploymentsResponse
	3,  // 39: torchwood.server.v1.FunctionsService.GetDeployment:output_type -> torchwood.server.v1.Deployment
	22, // 40: torchwood.server.v1.FunctionsService.DeleteDeployment:output_type -> torchwood.shared.v1.Empty
	4,  // 41: torchwood.server.v1.FunctionsService.SetVariables:output_type -> torchwood.server.v1.Variables
	4,  // 42: torchwood.server.v1.FunctionsService.GetVariables:output_type -> torchwood.server.v1.Variables
	6,  // 43: torchwood.server.v1.FunctionsService.CreateExecution:output_type -> torchwood.server.v1.Execution
	19, // 44: torchwood.server.v1.FunctionsService.ListExecutions:output_type -> torchwood.server.v1.ListExecutionsResponse
	6,  // 45: torchwood.server.v1.FunctionsService.GetExecution:output_type -> torchwood.server.v1.Execution
	30, // [30:46] is the sub-list for method output_type
	14, // [14:30] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_server_v1_functions_proto_init() }
func file_server_v1_functions_proto_init() {
	if File_server_v1_functions_proto != nil {
		return
	}
	file_server_v1_functions_proto_msgTypes[7].OneofWrappers = []any{}
	file_server_v1_functions_proto_msgTypes[8].OneofWrappers = []any{}
	file_server_v1_functions_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_functions_proto_rawDesc), len(file_server_v1_functions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_functions_proto_goTypes,
		DependencyIndexes: file_server_v1_functions_proto_depIdxs,
		MessageInfos:      file_server_v1_functions_proto_msgTypes,
	}.Build()
	File_server_v1_functions_proto = out.File
	file_server_v1_functions_proto_goTypes = nil
	file_server_v1_functions_proto_depIdxs = nil
}
