// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: server/v1/groups.proto

package serverv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/torchwooddev/torchwood/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_server_v1_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_server_v1_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_server_v1_groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{2}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListGroupsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetGroupPrefsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefs         *structpb.Struct       `protobuf:"bytes,1,opt,name=prefs,proto3" json:"prefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupPrefsResponse) Reset() {
	*x = GetGroupPrefsResponse{}
	mi := &file_server_v1_groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupPrefsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupPrefsResponse) ProtoMessage() {}

func (x *GetGroupPrefsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupPrefsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupPrefsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupPrefsResponse) GetPrefs() *structpb.Struct {
	if x != nil {
		return x.Prefs
	}
	return nil
}

type UpdateGroupPrefsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prefs         *structpb.Struct       `protobuf:"bytes,2,opt,name=prefs,proto3" json:"prefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupPrefsRequest) Reset() {
	*x = UpdateGroupPrefsRequest{}
	mi := &file_server_v1_groups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupPrefsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupPrefsRequest) ProtoMessage() {}

func (x *UpdateGroupPrefsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupPrefsRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupPrefsRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGroupPrefsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGroupPrefsRequest) GetPrefs() *structpb.Struct {
	if x != nil {
		return x.Prefs
	}
	return nil
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_server_v1_groups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{5}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Group) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Group) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Group) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Roles         []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	InvitedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=invited_at,json=invitedAt,proto3" json:"invited_at,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_server_v1_groups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{6}
}

func (x *Membership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Membership) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Membership) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Membership) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Membership) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Membership) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Membership) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Membership) GetInvitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InvitedAt
	}
	return nil
}

func (x *Membership) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *Membership) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Membership) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Roles         []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMembershipRequest) Reset() {
	*x = CreateMembershipRequest{}
	mi := &file_server_v1_groups_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMembershipRequest) ProtoMessage() {}

func (x *CreateMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMembershipRequest.ProtoReflect.Descriptor instead.
func (*CreateMembershipRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMembershipRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateMembershipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateMembershipRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateMembershipRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMembershipRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *CreateMembershipRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListMembershipsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// 不支持：groups 面不消费查询过滤，携带即 InvalidArgument（服务端显式
	// 拒绝，不再静默忽略）。成员定位用 group_id 路径参数 + 分页。
	Queries       []string `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	PageSize      int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string   `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipsRequest) Reset() {
	*x = ListMembershipsRequest{}
	mi := &file_server_v1_groups_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipsRequest) ProtoMessage() {}

func (x *ListMembershipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipsRequest.ProtoReflect.Descriptor instead.
func (*ListMembershipsRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{8}
}

func (x *ListMembershipsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListMembershipsRequest) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *ListMembershipsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMembershipsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MembershipId  string                 `protobuf:"bytes,2,opt,name=membership_id,json=membershipId,proto3" json:"membership_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipRequest) Reset() {
	*x = GetMembershipRequest{}
	mi := &file_server_v1_groups_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipRequest) ProtoMessage() {}

func (x *GetMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{9}
}

func (x *GetMembershipRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetMembershipRequest) GetMembershipId() string {
	if x != nil {
		return x.MembershipId
	}
	return ""
}

type ListMembershipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memberships   []*Membership          `protobuf:"bytes,1,rep,name=memberships,proto3" json:"memberships,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipsResponse) Reset() {
	*x = ListMembershipsResponse{}
	mi := &file_server_v1_groups_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipsResponse) ProtoMessage() {}

func (x *ListMembershipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipsResponse.ProtoReflect.Descriptor instead.
func (*ListMembershipsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{10}
}

func (x *ListMembershipsResponse) GetMemberships() []*Membership {
	if x != nil {
		return x.Memberships
	}
	return nil
}

func (x *ListMembershipsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpdateMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MembershipId  string                 `protobuf:"bytes,2,opt,name=membership_id,json=membershipId,proto3" json:"membership_id,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMembershipRequest) Reset() {
	*x = UpdateMembershipRequest{}
	mi := &file_server_v1_groups_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembershipRequest) ProtoMessage() {}

func (x *UpdateMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembershipRequest.ProtoReflect.Descriptor instead.
func (*UpdateMembershipRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMembershipRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateMembershipRequest) GetMembershipId() string {
	if x != nil {
		return x.MembershipId
	}
	return ""
}

func (x *UpdateMembershipRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UpdateMembershipStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MembershipId  string                 `protobuf:"bytes,2,opt,name=membership_id,json=membershipId,proto3" json:"membership_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMembershipStatusRequest) Reset() {
	*x = UpdateMembershipStatusRequest{}
	mi := &file_server_v1_groups_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMembershipStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembershipStatusRequest) ProtoMessage() {}

func (x *UpdateMembershipStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_groups_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembershipStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateMembershipStatusRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_groups_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateMembershipStatusRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateMembershipStatusRequest) GetMembershipId() string {
	if x != nil {
		return x.MembershipId
	}
	return ""
}

func (x *UpdateMembershipStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_server_v1_groups_proto protoreflect.FileDescriptor

const file_server_v1_groups_proto_rawDesc = "" +
	"\n" +
	"\x16server/v1/groups.proto\x12\x13torchwood.server.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x15shared/v1/authz.proto\x1a\x16shared/v1/common.proto\"J\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"!\n" +
	"\x0fGetGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x83\x01\n" +
	"\x12ListGroupsResponse\x122\n" +
	"\x06groups\x18\x01 \x03(\v2\x1a.torchwood.server.v1.GroupR\x06groups\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta\"F\n" +
	"\x15GetGroupPrefsResponse\x12-\n" +
	"\x05prefs\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05prefs\"X\n" +
	"\x17UpdateGroupPrefsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x05prefs\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05prefs\"\xd9\x01\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x92\x03\n" +
	"\n" +
	"Membership\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"invited_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tinvitedAt\x127\n" +
	"\tjoined_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa5\x01\n" +
	"\x17CreateMembershipRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x89\x01\n" +
	"\x16ListMembershipsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x18\n" +
	"\aqueries\x18\x02 \x03(\tR\aqueries\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"V\n" +
	"\x14GetMembershipRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12#\n" +
	"\rmembership_id\x18\x02 \x01(\tR\fmembershipId\"\x97\x01\n" +
	"\x17ListMembershipsResponse\x12A\n" +
	"\vmemberships\x18\x01 \x03(\v2\x1f.torchwood.server.v1.MembershipR\vmemberships\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta\"o\n" +
	"\x17UpdateMembershipRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12#\n" +
	"\rmembership_id\x18\x02 \x01(\tR\fmembershipId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\"w\n" +
	"\x1dUpdateMembershipStatusRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12#\n" +
	"\rmembership_id\x18\x02 \x01(\tR\fmembershipId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xdb\r\n" +
	"\rGroupsService\x12p\n" +
	"\vCreateGroup\x12'.torchwood.server.v1.CreateGroupRequest\x1a\x1a.torchwood.server.v1.Group\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/server/groups\x12r\n" +
	"\n" +
	"ListGroups\x12 .torchwood.shared.v1.ListRequest\x1a'.torchwood.server.v1.ListGroupsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/server/groups\x12l\n" +
	"\bGetGroup\x12$.torchwood.server.v1.GetGroupRequest\x1a\x1a.torchwood.server.v1.Group\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/server/groups/{id}\x12o\n" +
	"\vDeleteGroup\x12$.torchwood.server.v1.GetGroupRequest\x1a\x1a.torchwood.shared.v1.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/v1/server/groups/{id}\x12\x87\x01\n" +
	"\rGetGroupPrefs\x12$.torchwood.server.v1.GetGroupRequest\x1a*.torchwood.server.v1.GetGroupPrefsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/server/groups/{id}/prefs\x12\x95\x01\n" +
	"\x10UpdateGroupPrefs\x12,.torchwood.server.v1.UpdateGroupPrefsRequest\x1a*.torchwood.server.v1.GetGroupPrefsResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/v1/server/groups/{id}/prefs\x12\x96\x01\n" +
	"\x10CreateMembership\x12,.torchwood.server.v1.CreateMembershipRequest\x1a\x1f.torchwood.server.v1.Membership\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/server/groups/{group_id}/memberships\x12\x9e\x01\n" +
	"\x0fListMemberships\x12+.torchwood.server.v1.ListMembershipsRequest\x1a,.torchwood.server.v1.ListMembershipsResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/server/groups/{group_id}/memberships\x12\x9d\x01\n" +
	"\rGetMembership\x12).torchwood.server.v1.GetMembershipRequest\x1a\x1f.torchwood.server.v1.Membership\"@\x82\xd3\xe4\x93\x02:\x128/v1/server/groups/{group_id}/memberships/{membership_id}\x12\xa6\x01\n" +
	"\x10UpdateMembership\x12,.torchwood.server.v1.UpdateMembershipRequest\x1a\x1f.torchwood.server.v1.Membership\"C\x82\xd3\xe4\x93\x02=:\x01*28/v1/server/groups/{group_id}/memberships/{membership_id}\x12\xb9\x01\n" +
	"\x16UpdateMembershipStatus\x122.torchwood.server.v1.UpdateMembershipStatusRequest\x1a\x1f.torchwood.server.v1.Membership\"J\x82\xd3\xe4\x93\x02D:\x01*2?/v1/server/groups/{group_id}/memberships/{membership_id}/status\x12\x9b\x01\n" +
	"\x10DeleteMembership\x12).torchwood.server.v1.GetMembershipRequest\x1a\x1a.torchwood.shared.v1.Empty\"@\x82\xd3\xe4\x93\x02:*8/v1/server/groups/{group_id}/memberships/{membership_id}\x1a\x06\x92\xb2\x19\x02\b\x04B\xda\x03\x92A\x97\x03RR\n" +
	"\adefault\x12G\n" +
	"\x1dAn unexpected error response.\x12&\n" +
	"$\x1a\".torchwood.shared.v1.ErrorResponseZ\x91\x02\n" +
	"3\n" +
	"\x06Bearer\x12)\b\x02\x12\x14格式: Bearer <jwt>\x1a\rAuthorization \x02\n" +
	"\x86\x01\n" +
	"\x06apiKey\x12|\b\x02\x12k项目绑定在密钥行上，不需要 X-Torchwood-Project。该头仅 Console admin 会话切换项目。\x1a\tX-API-Key \x02\n" +
	"Q\n" +
	"\x06cookie\x12G\b\x02\x129TORCHWOOD_session_console=<sid>（Console admin 会话）\x1a\x06Cookie \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06apiKey\x12\x00z\x1f\n" +
	"\x12x-torchwood-access\x12\t\x1a\aapi_keyZ=github.com/torchwooddev/torchwood/genproto/server/v1;serverv1b\x06proto3"

var (
	file_server_v1_groups_proto_rawDescOnce sync.Once
	file_server_v1_groups_proto_rawDescData []byte
)

func file_server_v1_groups_proto_rawDescGZIP() []byte {
	file_server_v1_groups_proto_rawDescOnce.Do(func() {
		file_server_v1_groups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_groups_proto_rawDesc), len(file_server_v1_groups_proto_rawDesc)))
	})
	return file_server_v1_groups_proto_rawDescData
}

var file_server_v1_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_server_v1_groups_proto_goTypes = []any{
	(*CreateGroupRequest)(nil),            // 0: torchwood.server.v1.CreateGroupRequest
	(*GetGroupRequest)(nil),               // 1: torchwood.server.v1.GetGroupRequest
	(*ListGroupsResponse)(nil),            // 2: torchwood.server.v1.ListGroupsResponse
	(*GetGroupPrefsResponse)(nil),         // 3: torchwood.server.v1.GetGroupPrefsResponse
	(*UpdateGroupPrefsRequest)(nil),       // 4: torchwood.server.v1.UpdateGroupPrefsRequest
	(*Group)(nil),                         // 5: torchwood.server.v1.Group
	(*Membership)(nil),                    // 6: torchwood.server.v1.Membership
	(*CreateMembershipRequest)(nil),       // 7: torchwood.server.v1.CreateMembershipRequest
	(*ListMembershipsRequest)(nil),        // 8: torchwood.server.v1.ListMembershipsRequest
	(*GetMembershipRequest)(nil),          // 9: torchwood.server.v1.GetMembershipRequest
	(*ListMembershipsResponse)(nil),       // 10: torchwood.server.v1.ListMembershipsResponse
	(*UpdateMembershipRequest)(nil),       // 11: torchwood.server.v1.UpdateMembershipRequest
	(*UpdateMembershipStatusRequest)(nil), // 12: torchwood.server.v1.UpdateMembershipStatusRequest
	(*v1.ListResponseMeta)(nil),           // 13: torchwood.shared.v1.ListResponseMeta
	(*structpb.Struct)(nil),               // 14: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),         // 15: google.protobuf.Timestamp
	(*v1.ListRequest)(nil),                // 16: torchwood.shared.v1.ListRequest
	(*v1.Empty)(nil),                      // 17: torchwood.shared.v1.Empty
}
var file_server_v1_groups_proto_depIdxs = []int32{
	5,  // 0: torchwood.server.v1.ListGroupsResponse.groups:type_name -> torchwood.server.v1.Group
	13, // 1: torchwood.server.v1.ListGroupsResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	14, // 2: torchwood.server.v1.GetGroupPrefsResponse.prefs:type_name -> google.protobuf.Struct
	14, // 3: torchwood.server.v1.UpdateGroupPrefsRequest.prefs:type_name -> google.protobuf.Struct
	15, // 4: torchwood.server.v1.Group.created_at:type_name -> google.protobuf.Timestamp
	15, // 5: torchwood.server.v1.Group.updated_at:type_name -> google.protobuf.Timestamp
	15, // 6: torchwood.server.v1.Membership.invited_at:type_name -> google.protobuf.Timestamp
	15, // 7: torchwood.server.v1.Membership.joined_at:type_name -> google.protobuf.Timestamp
	15, // 8: torchwood.server.v1.Membership.created_at:type_name -> google.protobuf.Timestamp
	15, // 9: torchwood.server.v1.Membership.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 10: torchwood.server.v1.ListMembershipsResponse.memberships:type_name -> torchwood.server.v1.Membership
	13, // 11: torchwood.server.v1.ListMembershipsResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	0,  // 12: torchwood.server.v1.GroupsService.CreateGroup:input_type -> torchwood.server.v1.CreateGroupRequest
	16, // 13: torchwood.server.v1.GroupsService.ListGroups:input_type -> torchwood.shared.v1.ListRequest
	1,  // 14: torchwood.server.v1.GroupsService.GetGroup:input_type -> torchwood.server.v1.GetGroupRequest
	1,  // 15: torchwood.server.v1.GroupsService.DeleteGroup:input_type -> torchwood.server.v1.GetGroupRequest
	1,  // 16: torchwood.server.v1.GroupsService.GetGroupPrefs:input_type -> torchwood.server.v1.GetGroupRequest
	4,  // 17: torchwood.server.v1.GroupsService.UpdateGroupPrefs:input_type -> torchwood.server.v1.UpdateGroupPrefsRequest
	7,  // 18: torchwood.server.v1.GroupsService.CreateMembership:input_type -> torchwood.server.v1.CreateMembershipRequest
	8,  // 19: torchwood.server.v1.GroupsService.ListMemberships:input_type -> torchwood.server.v1.ListMembershipsRequest
	9,  // 20: torchwood.server.v1.GroupsService.GetMembership:input_type -> torchwood.server.v1.GetMembershipRequest
	11, // 21: torchwood.server.v1.GroupsService.UpdateMembership:input_type -> torchwood.server.v1.UpdateMembershipRequest
	12, // 22: torchwood.server.v1.GroupsService.UpdateMembershipStatus:input_type -> torchwood.server.v1.UpdateMembershipStatusRequest
	9,  // 23: torchwood.server.v1.GroupsService.DeleteMembership:input_type -> torchwood.server.v1.GetMembershipRequest
	5,  // 24: torchwood.server.v1.GroupsService.CreateGroup:output_type -> torchwood.server.v1.Group
	2,  // 25: torchwood.server.v1.GroupsService.ListGroups:output_type -> torchwood.server.v1.ListGroupsResponse
	5,  // 26: torchwood.server.v1.GroupsService.GetGroup:output_type -> torchwood.server.v1.Group
	17, // 27: torchwood.server.v1.GroupsService.DeleteGroup:output_type -> torchwood.shared.v1.Empty
	3,  // 28: torchwood.server.v1.GroupsService.GetGroupPrefs:output_type -> torchwood.server.v1.GetGroupPrefsResponse
	3,  // 29: torchwood.server.v1.GroupsService.UpdateGroupPrefs:output_type -> torchwood.server.v1.GetGroupPrefsResponse
	6,  // 30: torchwood.server.v1.GroupsService.CreateMembership:output_type -> torchwood.server.v1.Membership
	10, // 31: torchwood.server.v1.GroupsService.ListMemberships:output_type -> torchwood.server.v1.ListMembershipsResponse
	6,  // 32: torchwood.server.v1.GroupsService.GetMembership:output_type -> torchwood.server.v1.Membership
	6,  // 33: torchwood.server.v1.GroupsService.UpdateMembership:output_type -> torchwood.server.v1.Membership
	6,  // 34: torchwood.server.v1.GroupsService.UpdateMembershipStatus:output_type -> torchwood.server.v1.Membership
	17, // 35: torchwood.server.v1.GroupsService.DeleteMembership:output_type -> torchwood.shared.v1.Empty
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_server_v1_groups_proto_init() }
func file_server_v1_groups_proto_init() {
	if File_server_v1_groups_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_groups_proto_rawDesc), len(file_server_v1_groups_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_groups_proto_goTypes,
		DependencyIndexes: file_server_v1_groups_proto_depIdxs,
		MessageInfos:      file_server_v1_groups_proto_msgTypes,
	}.Build()
	File_server_v1_groups_proto = out.File
	file_server_v1_groups_proto_goTypes = nil
	file_server_v1_groups_proto_depIdxs = nil
}
