// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: server/v1/teams.proto

package serverv1

import (
	v1 "github.com/torchwooddev/torchwood/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_server_v1_teams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_server_v1_teams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{1}
}

func (x *GetTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsResponse) Reset() {
	*x = ListTeamsResponse{}
	mi := &file_server_v1_teams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsResponse) ProtoMessage() {}

func (x *ListTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{2}
}

func (x *ListTeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *ListTeamsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_server_v1_teams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{3}
}

func (x *Team) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Team) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Team) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Team) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Roles         []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	InvitedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=invited_at,json=invitedAt,proto3" json:"invited_at,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_server_v1_teams_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{4}
}

func (x *Membership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Membership) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Membership) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Membership) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Membership) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Membership) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Membership) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Membership) GetInvitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InvitedAt
	}
	return nil
}

func (x *Membership) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *Membership) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Membership) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Roles         []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMembershipRequest) Reset() {
	*x = CreateMembershipRequest{}
	mi := &file_server_v1_teams_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMembershipRequest) ProtoMessage() {}

func (x *CreateMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMembershipRequest.ProtoReflect.Descriptor instead.
func (*CreateMembershipRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMembershipRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateMembershipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateMembershipRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateMembershipRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMembershipRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *CreateMembershipRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListMembershipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Queries       []string               `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipsRequest) Reset() {
	*x = ListMembershipsRequest{}
	mi := &file_server_v1_teams_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipsRequest) ProtoMessage() {}

func (x *ListMembershipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipsRequest.ProtoReflect.Descriptor instead.
func (*ListMembershipsRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{6}
}

func (x *ListMembershipsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListMembershipsRequest) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *ListMembershipsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMembershipsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MembershipId  string                 `protobuf:"bytes,2,opt,name=membership_id,json=membershipId,proto3" json:"membership_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipRequest) Reset() {
	*x = GetMembershipRequest{}
	mi := &file_server_v1_teams_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipRequest) ProtoMessage() {}

func (x *GetMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{7}
}

func (x *GetMembershipRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *GetMembershipRequest) GetMembershipId() string {
	if x != nil {
		return x.MembershipId
	}
	return ""
}

type ListMembershipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memberships   []*Membership          `protobuf:"bytes,1,rep,name=memberships,proto3" json:"memberships,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipsResponse) Reset() {
	*x = ListMembershipsResponse{}
	mi := &file_server_v1_teams_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipsResponse) ProtoMessage() {}

func (x *ListMembershipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipsResponse.ProtoReflect.Descriptor instead.
func (*ListMembershipsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{8}
}

func (x *ListMembershipsResponse) GetMemberships() []*Membership {
	if x != nil {
		return x.Memberships
	}
	return nil
}

func (x *ListMembershipsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpdateMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MembershipId  string                 `protobuf:"bytes,2,opt,name=membership_id,json=membershipId,proto3" json:"membership_id,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMembershipRequest) Reset() {
	*x = UpdateMembershipRequest{}
	mi := &file_server_v1_teams_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembershipRequest) ProtoMessage() {}

func (x *UpdateMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembershipRequest.ProtoReflect.Descriptor instead.
func (*UpdateMembershipRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMembershipRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UpdateMembershipRequest) GetMembershipId() string {
	if x != nil {
		return x.MembershipId
	}
	return ""
}

func (x *UpdateMembershipRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UpdateMembershipStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MembershipId  string                 `protobuf:"bytes,2,opt,name=membership_id,json=membershipId,proto3" json:"membership_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMembershipStatusRequest) Reset() {
	*x = UpdateMembershipStatusRequest{}
	mi := &file_server_v1_teams_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMembershipStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembershipStatusRequest) ProtoMessage() {}

func (x *UpdateMembershipStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembershipStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateMembershipStatusRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMembershipStatusRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UpdateMembershipStatusRequest) GetMembershipId() string {
	if x != nil {
		return x.MembershipId
	}
	return ""
}

func (x *UpdateMembershipStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_server_v1_teams_proto protoreflect.FileDescriptor

const file_server_v1_teams_proto_rawDesc = "" +
	"\n" +
	"\x15server/v1/teams.proto\x12\x13torchwood.server.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15shared/v1/authz.proto\x1a\x16shared/v1/common.proto\"I\n" +
	"\x11CreateTeamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\" \n" +
	"\x0eGetTeamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x7f\n" +
	"\x11ListTeamsResponse\x12/\n" +
	"\x05teams\x18\x01 \x03(\v2\x19.torchwood.server.v1.TeamR\x05teams\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta\"\xd8\x01\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x90\x03\n" +
	"\n" +
	"Membership\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"invited_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tinvitedAt\x127\n" +
	"\tjoined_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa3\x01\n" +
	"\x17CreateMembershipRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x87\x01\n" +
	"\x16ListMembershipsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x18\n" +
	"\aqueries\x18\x02 \x03(\tR\aqueries\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"T\n" +
	"\x14GetMembershipRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12#\n" +
	"\rmembership_id\x18\x02 \x01(\tR\fmembershipId\"\x97\x01\n" +
	"\x17ListMembershipsResponse\x12A\n" +
	"\vmemberships\x18\x01 \x03(\v2\x1f.torchwood.server.v1.MembershipR\vmemberships\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta\"m\n" +
	"\x17UpdateMembershipRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12#\n" +
	"\rmembership_id\x18\x02 \x01(\tR\fmembershipId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\"u\n" +
	"\x1dUpdateMembershipStatusRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12#\n" +
	"\rmembership_id\x18\x02 \x01(\tR\fmembershipId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\x9e\v\n" +
	"\fTeamsService\x12l\n" +
	"\n" +
	"CreateTeam\x12&.torchwood.server.v1.CreateTeamRequest\x1a\x19.torchwood.server.v1.Team\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/server/teams\x12o\n" +
	"\tListTeams\x12 .torchwood.shared.v1.ListRequest\x1a&.torchwood.server.v1.ListTeamsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/server/teams\x12h\n" +
	"\aGetTeam\x12#.torchwood.server.v1.GetTeamRequest\x1a\x19.torchwood.server.v1.Team\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/server/teams/{id}\x12l\n" +
	"\n" +
	"DeleteTeam\x12#.torchwood.server.v1.GetTeamRequest\x1a\x1a.torchwood.shared.v1.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/server/teams/{id}\x12\x94\x01\n" +
	"\x10CreateMembership\x12,.torchwood.server.v1.CreateMembershipRequest\x1a\x1f.torchwood.server.v1.Membership\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/server/teams/{team_id}/memberships\x12\x9c\x01\n" +
	"\x0fListMemberships\x12+.torchwood.server.v1.ListMembershipsRequest\x1a,.torchwood.server.v1.ListMembershipsResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/server/teams/{team_id}/memberships\x12\x9b\x01\n" +
	"\rGetMembership\x12).torchwood.server.v1.GetMembershipRequest\x1a\x1f.torchwood.server.v1.Membership\">\x82\xd3\xe4\x93\x028\x126/v1/server/teams/{team_id}/memberships/{membership_id}\x12\xa4\x01\n" +
	"\x10UpdateMembership\x12,.torchwood.server.v1.UpdateMembershipRequest\x1a\x1f.torchwood.server.v1.Membership\"A\x82\xd3\xe4\x93\x02;:\x01*26/v1/server/teams/{team_id}/memberships/{membership_id}\x12\xb7\x01\n" +
	"\x16UpdateMembershipStatus\x122.torchwood.server.v1.UpdateMembershipStatusRequest\x1a\x1f.torchwood.server.v1.Membership\"H\x82\xd3\xe4\x93\x02B:\x01*2=/v1/server/teams/{team_id}/memberships/{membership_id}/status\x12\x99\x01\n" +
	"\x10DeleteMembership\x12).torchwood.server.v1.GetMembershipRequest\x1a\x1a.torchwood.shared.v1.Empty\">\x82\xd3\xe4\x93\x028*6/v1/server/teams/{team_id}/memberships/{membership_id}\x1a\x06\x92\xb2\x19\x02\b\x04B?Z=github.com/torchwooddev/torchwood/genproto/server/v1;serverv1b\x06proto3"

var (
	file_server_v1_teams_proto_rawDescOnce sync.Once
	file_server_v1_teams_proto_rawDescData []byte
)

func file_server_v1_teams_proto_rawDescGZIP() []byte {
	file_server_v1_teams_proto_rawDescOnce.Do(func() {
		file_server_v1_teams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_teams_proto_rawDesc), len(file_server_v1_teams_proto_rawDesc)))
	})
	return file_server_v1_teams_proto_rawDescData
}

var file_server_v1_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_server_v1_teams_proto_goTypes = []any{
	(*CreateTeamRequest)(nil),             // 0: torchwood.server.v1.CreateTeamRequest
	(*GetTeamRequest)(nil),                // 1: torchwood.server.v1.GetTeamRequest
	(*ListTeamsResponse)(nil),             // 2: torchwood.server.v1.ListTeamsResponse
	(*Team)(nil),                          // 3: torchwood.server.v1.Team
	(*Membership)(nil),                    // 4: torchwood.server.v1.Membership
	(*CreateMembershipRequest)(nil),       // 5: torchwood.server.v1.CreateMembershipRequest
	(*ListMembershipsRequest)(nil),        // 6: torchwood.server.v1.ListMembershipsRequest
	(*GetMembershipRequest)(nil),          // 7: torchwood.server.v1.GetMembershipRequest
	(*ListMembershipsResponse)(nil),       // 8: torchwood.server.v1.ListMembershipsResponse
	(*UpdateMembershipRequest)(nil),       // 9: torchwood.server.v1.UpdateMembershipRequest
	(*UpdateMembershipStatusRequest)(nil), // 10: torchwood.server.v1.UpdateMembershipStatusRequest
	(*v1.ListResponseMeta)(nil),           // 11: torchwood.shared.v1.ListResponseMeta
	(*timestamppb.Timestamp)(nil),         // 12: google.protobuf.Timestamp
	(*v1.ListRequest)(nil),                // 13: torchwood.shared.v1.ListRequest
	(*v1.Empty)(nil),                      // 14: torchwood.shared.v1.Empty
}
var file_server_v1_teams_proto_depIdxs = []int32{
	3,  // 0: torchwood.server.v1.ListTeamsResponse.teams:type_name -> torchwood.server.v1.Team
	11, // 1: torchwood.server.v1.ListTeamsResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	12, // 2: torchwood.server.v1.Team.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: torchwood.server.v1.Team.updated_at:type_name -> google.protobuf.Timestamp
	12, // 4: torchwood.server.v1.Membership.invited_at:type_name -> google.protobuf.Timestamp
	12, // 5: torchwood.server.v1.Membership.joined_at:type_name -> google.protobuf.Timestamp
	12, // 6: torchwood.server.v1.Membership.created_at:type_name -> google.protobuf.Timestamp
	12, // 7: torchwood.server.v1.Membership.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 8: torchwood.server.v1.ListMembershipsResponse.memberships:type_name -> torchwood.server.v1.Membership
	11, // 9: torchwood.server.v1.ListMembershipsResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	0,  // 10: torchwood.server.v1.TeamsService.CreateTeam:input_type -> torchwood.server.v1.CreateTeamRequest
	13, // 11: torchwood.server.v1.TeamsService.ListTeams:input_type -> torchwood.shared.v1.ListRequest
	1,  // 12: torchwood.server.v1.TeamsService.GetTeam:input_type -> torchwood.server.v1.GetTeamRequest
	1,  // 13: torchwood.server.v1.TeamsService.DeleteTeam:input_type -> torchwood.server.v1.GetTeamRequest
	5,  // 14: torchwood.server.v1.TeamsService.CreateMembership:input_type -> torchwood.server.v1.CreateMembershipRequest
	6,  // 15: torchwood.server.v1.TeamsService.ListMemberships:input_type -> torchwood.server.v1.ListMembershipsRequest
	7,  // 16: torchwood.server.v1.TeamsService.GetMembership:input_type -> torchwood.server.v1.GetMembershipRequest
	9,  // 17: torchwood.server.v1.TeamsService.UpdateMembership:input_type -> torchwood.server.v1.UpdateMembershipRequest
	10, // 18: torchwood.server.v1.TeamsService.UpdateMembershipStatus:input_type -> torchwood.server.v1.UpdateMembershipStatusRequest
	7,  // 19: torchwood.server.v1.TeamsService.DeleteMembership:input_type -> torchwood.server.v1.GetMembershipRequest
	3,  // 20: torchwood.server.v1.TeamsService.CreateTeam:output_type -> torchwood.server.v1.Team
	2,  // 21: torchwood.server.v1.TeamsService.ListTeams:output_type -> torchwood.server.v1.ListTeamsResponse
	3,  // 22: torchwood.server.v1.TeamsService.GetTeam:output_type -> torchwood.server.v1.Team
	14, // 23: torchwood.server.v1.TeamsService.DeleteTeam:output_type -> torchwood.shared.v1.Empty
	4,  // 24: torchwood.server.v1.TeamsService.CreateMembership:output_type -> torchwood.server.v1.Membership
	8,  // 25: torchwood.server.v1.TeamsService.ListMemberships:output_type -> torchwood.server.v1.ListMembershipsResponse
	4,  // 26: torchwood.server.v1.TeamsService.GetMembership:output_type -> torchwood.server.v1.Membership
	4,  // 27: torchwood.server.v1.TeamsService.UpdateMembership:output_type -> torchwood.server.v1.Membership
	4,  // 28: torchwood.server.v1.TeamsService.UpdateMembershipStatus:output_type -> torchwood.server.v1.Membership
	14, // 29: torchwood.server.v1.TeamsService.DeleteMembership:output_type -> torchwood.shared.v1.Empty
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_server_v1_teams_proto_init() }
func file_server_v1_teams_proto_init() {
	if File_server_v1_teams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_teams_proto_rawDesc), len(file_server_v1_teams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_teams_proto_goTypes,
		DependencyIndexes: file_server_v1_teams_proto_depIdxs,
		MessageInfos:      file_server_v1_teams_proto_msgTypes,
	}.Build()
	File_server_v1_teams_proto = out.File
	file_server_v1_teams_proto_goTypes = nil
	file_server_v1_teams_proto_depIdxs = nil
}
