// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: console/v1/admins.proto

package consolev1

import (
	context "context"
	v1 "github.com/torchwooddev/torchwood/genproto/shared/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsoleAdminsService_GetCurrentAdmin_FullMethodName = "/torchwood.console.v1.ConsoleAdminsService/GetCurrentAdmin"
	ConsoleAdminsService_ListAdmins_FullMethodName      = "/torchwood.console.v1.ConsoleAdminsService/ListAdmins"
	ConsoleAdminsService_CreateAdmin_FullMethodName     = "/torchwood.console.v1.ConsoleAdminsService/CreateAdmin"
	ConsoleAdminsService_UpdateAdmin_FullMethodName     = "/torchwood.console.v1.ConsoleAdminsService/UpdateAdmin"
	ConsoleAdminsService_DeleteAdmin_FullMethodName     = "/torchwood.console.v1.ConsoleAdminsService/DeleteAdmin"
)

// ConsoleAdminsServiceClient is the client API for ConsoleAdminsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConsoleAdminsService 管理系统管理员（console_admins 表）。
// 权限模型：owner/admin 角色可查看列表；创建、修改、删除仅 owner 可执行。
// 方法与 client/server API 不同，这里直接使用 console admin role 作为权限串。
type ConsoleAdminsServiceClient interface {
	GetCurrentAdmin(ctx context.Context, in *GetCurrentAdminRequest, opts ...grpc.CallOption) (*Admin, error)
	ListAdmins(ctx context.Context, in *ListAdminsRequest, opts ...grpc.CallOption) (*ListAdminsResponse, error)
	CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*Admin, error)
	UpdateAdmin(ctx context.Context, in *UpdateAdminRequest, opts ...grpc.CallOption) (*Admin, error)
	DeleteAdmin(ctx context.Context, in *DeleteAdminRequest, opts ...grpc.CallOption) (*v1.Empty, error)
}

type consoleAdminsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsoleAdminsServiceClient(cc grpc.ClientConnInterface) ConsoleAdminsServiceClient {
	return &consoleAdminsServiceClient{cc}
}

func (c *consoleAdminsServiceClient) GetCurrentAdmin(ctx context.Context, in *GetCurrentAdminRequest, opts ...grpc.CallOption) (*Admin, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Admin)
	err := c.cc.Invoke(ctx, ConsoleAdminsService_GetCurrentAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAdminsServiceClient) ListAdmins(ctx context.Context, in *ListAdminsRequest, opts ...grpc.CallOption) (*ListAdminsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminsResponse)
	err := c.cc.Invoke(ctx, ConsoleAdminsService_ListAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAdminsServiceClient) CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*Admin, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Admin)
	err := c.cc.Invoke(ctx, ConsoleAdminsService_CreateAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAdminsServiceClient) UpdateAdmin(ctx context.Context, in *UpdateAdminRequest, opts ...grpc.CallOption) (*Admin, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Admin)
	err := c.cc.Invoke(ctx, ConsoleAdminsService_UpdateAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleAdminsServiceClient) DeleteAdmin(ctx context.Context, in *DeleteAdminRequest, opts ...grpc.CallOption) (*v1.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, ConsoleAdminsService_DeleteAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsoleAdminsServiceServer is the server API for ConsoleAdminsService service.
// All implementations must embed UnimplementedConsoleAdminsServiceServer
// for forward compatibility.
//
// ConsoleAdminsService 管理系统管理员（console_admins 表）。
// 权限模型：owner/admin 角色可查看列表；创建、修改、删除仅 owner 可执行。
// 方法与 client/server API 不同，这里直接使用 console admin role 作为权限串。
type ConsoleAdminsServiceServer interface {
	GetCurrentAdmin(context.Context, *GetCurrentAdminRequest) (*Admin, error)
	ListAdmins(context.Context, *ListAdminsRequest) (*ListAdminsResponse, error)
	CreateAdmin(context.Context, *CreateAdminRequest) (*Admin, error)
	UpdateAdmin(context.Context, *UpdateAdminRequest) (*Admin, error)
	DeleteAdmin(context.Context, *DeleteAdminRequest) (*v1.Empty, error)
	mustEmbedUnimplementedConsoleAdminsServiceServer()
}

// UnimplementedConsoleAdminsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsoleAdminsServiceServer struct{}

func (UnimplementedConsoleAdminsServiceServer) GetCurrentAdmin(context.Context, *GetCurrentAdminRequest) (*Admin, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentAdmin not implemented")
}
func (UnimplementedConsoleAdminsServiceServer) ListAdmins(context.Context, *ListAdminsRequest) (*ListAdminsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdmins not implemented")
}
func (UnimplementedConsoleAdminsServiceServer) CreateAdmin(context.Context, *CreateAdminRequest) (*Admin, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdmin not implemented")
}
func (UnimplementedConsoleAdminsServiceServer) UpdateAdmin(context.Context, *UpdateAdminRequest) (*Admin, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdmin not implemented")
}
func (UnimplementedConsoleAdminsServiceServer) DeleteAdmin(context.Context, *DeleteAdminRequest) (*v1.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdmin not implemented")
}
func (UnimplementedConsoleAdminsServiceServer) mustEmbedUnimplementedConsoleAdminsServiceServer() {}
func (UnimplementedConsoleAdminsServiceServer) testEmbeddedByValue()                              {}

// UnsafeConsoleAdminsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsoleAdminsServiceServer will
// result in compilation errors.
type UnsafeConsoleAdminsServiceServer interface {
	mustEmbedUnimplementedConsoleAdminsServiceServer()
}

func RegisterConsoleAdminsServiceServer(s grpc.ServiceRegistrar, srv ConsoleAdminsServiceServer) {
	// If the following call panics, it indicates UnimplementedConsoleAdminsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsoleAdminsService_ServiceDesc, srv)
}

func _ConsoleAdminsService_GetCurrentAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAdminsServiceServer).GetCurrentAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAdminsService_GetCurrentAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAdminsServiceServer).GetCurrentAdmin(ctx, req.(*GetCurrentAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAdminsService_ListAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAdminsServiceServer).ListAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAdminsService_ListAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAdminsServiceServer).ListAdmins(ctx, req.(*ListAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAdminsService_CreateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAdminsServiceServer).CreateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAdminsService_CreateAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAdminsServiceServer).CreateAdmin(ctx, req.(*CreateAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAdminsService_UpdateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAdminsServiceServer).UpdateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAdminsService_UpdateAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAdminsServiceServer).UpdateAdmin(ctx, req.(*UpdateAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleAdminsService_DeleteAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleAdminsServiceServer).DeleteAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsoleAdminsService_DeleteAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleAdminsServiceServer).DeleteAdmin(ctx, req.(*DeleteAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsoleAdminsService_ServiceDesc is the grpc.ServiceDesc for ConsoleAdminsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsoleAdminsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "torchwood.console.v1.ConsoleAdminsService",
	HandlerType: (*ConsoleAdminsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentAdmin",
			Handler:    _ConsoleAdminsService_GetCurrentAdmin_Handler,
		},
		{
			MethodName: "ListAdmins",
			Handler:    _ConsoleAdminsService_ListAdmins_Handler,
		},
		{
			MethodName: "CreateAdmin",
			Handler:    _ConsoleAdminsService_CreateAdmin_Handler,
		},
		{
			MethodName: "UpdateAdmin",
			Handler:    _ConsoleAdminsService_UpdateAdmin_Handler,
		},
		{
			MethodName: "DeleteAdmin",
			Handler:    _ConsoleAdminsService_DeleteAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "console/v1/admins.proto",
}
