// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: console/v1/auth.proto

package consolev1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/torchwooddev/torchwood/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_console_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SignInRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInResponse) Reset() {
	*x = SignInResponse{}
	mi := &file_console_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResponse) ProtoMessage() {}

func (x *SignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResponse.ProtoReflect.Descriptor instead.
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return file_console_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SignInResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SignInResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SignInResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_console_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type SignOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOutRequest) Reset() {
	*x = SignOutRequest{}
	mi := &file_console_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutRequest) ProtoMessage() {}

func (x *SignOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutRequest.ProtoReflect.Descriptor instead.
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_auth_proto_rawDescGZIP(), []int{3}
}

type GetSetupStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSetupStatusRequest) Reset() {
	*x = GetSetupStatusRequest{}
	mi := &file_console_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetupStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetupStatusRequest) ProtoMessage() {}

func (x *GetSetupStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetupStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSetupStatusRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_auth_proto_rawDescGZIP(), []int{4}
}

type GetSetupStatusResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	NeedsSetup bool                   `protobuf:"varint,1,opt,name=needs_setup,json=needsSetup,proto3" json:"needs_setup,omitempty"`
	// 部署方是否配置了 TORCHWOOD_SECURITY_SETUP_TOKEN；为 true 时登录页
	// 需展示 setup token 输入框。
	SetupTokenRequired bool `protobuf:"varint,2,opt,name=setup_token_required,json=setupTokenRequired,proto3" json:"setup_token_required,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetSetupStatusResponse) Reset() {
	*x = GetSetupStatusResponse{}
	mi := &file_console_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetupStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetupStatusResponse) ProtoMessage() {}

func (x *GetSetupStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetupStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSetupStatusResponse) Descriptor() ([]byte, []int) {
	return file_console_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetSetupStatusResponse) GetNeedsSetup() bool {
	if x != nil {
		return x.NeedsSetup
	}
	return false
}

func (x *GetSetupStatusResponse) GetSetupTokenRequired() bool {
	if x != nil {
		return x.SetupTokenRequired
	}
	return false
}

type SignUpRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Email    string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// Console 引导令牌（security.setup_token / TORCHWOOD_SECURITY_SETUP_TOKEN）。
	SetupToken string `protobuf:"bytes,3,opt,name=setup_token,json=setupToken,proto3" json:"setup_token,omitempty"`
	// 首个项目 ID，须匹配 ^[a-z][a-z0-9]{0,27}$。
	ProjectId string `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// 首个业务数据库 ID，规则同 project_id。系统集合所在的 default 库会随
	// 项目自动创建；填写 default 即使用该库，填写其他 id 则额外创建业务库。
	DatabaseId    string `protobuf:"bytes,5,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_console_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUpRequest) GetSetupToken() string {
	if x != nil {
		return x.SetupToken
	}
	return ""
}

func (x *SignUpRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SignUpRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *Admin                 `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`                                // 复用 admins.proto 的 Admin 消息
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // 与 SignInResponse 一致，便于前端统一处理
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_console_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_console_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *SignUpResponse) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *SignUpResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SignUpResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_console_v1_auth_proto protoreflect.FileDescriptor

const file_console_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x15console/v1/auth.proto\x12\x14torchwood.console.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17console/v1/admins.proto\x1a\x15shared/v1/authz.proto\x1a\x16shared/v1/common.proto\"A\n" +
	"\rSignInRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x93\x01\n" +
	"\x0eSignInResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x10\n" +
	"\x0eSignOutRequest\"\x17\n" +
	"\x15GetSetupStatusRequest\"k\n" +
	"\x16GetSetupStatusResponse\x12\x1f\n" +
	"\vneeds_setup\x18\x01 \x01(\bR\n" +
	"needsSetup\x120\n" +
	"\x14setup_token_required\x18\x02 \x01(\bR\x12setupTokenRequired\"\xa2\x01\n" +
	"\rSignUpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vsetup_token\x18\x03 \x01(\tR\n" +
	"setupToken\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vdatabase_id\x18\x05 \x01(\tR\n" +
	"databaseId\"\xa9\x01\n" +
	"\x0eSignUpResponse\x121\n" +
	"\x05admin\x18\x01 \x01(\v2\x1b.torchwood.console.v1.AdminR\x05admin\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshTokenJ\x04\b\x04\x10\x05R\x16default_api_key_secret2\x9f\x05\n" +
	"\x12ConsoleAuthService\x12x\n" +
	"\x06SignIn\x12#.torchwood.console.v1.SignInRequest\x1a$.torchwood.console.v1.SignInResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/console/auth/sign-in\x12\x84\x01\n" +
	"\fRefreshToken\x12).torchwood.console.v1.RefreshTokenRequest\x1a$.torchwood.console.v1.SignInResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/console/auth/refresh\x12q\n" +
	"\aSignOut\x12$.torchwood.console.v1.SignOutRequest\x1a\x1a.torchwood.shared.v1.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/console/auth/sign-out\x12\x92\x01\n" +
	"\x0eGetSetupStatus\x12+.torchwood.console.v1.GetSetupStatusRequest\x1a,.torchwood.console.v1.GetSetupStatusResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/console/auth/setup-status\x12x\n" +
	"\x06SignUp\x12#.torchwood.console.v1.SignUpRequest\x1a$.torchwood.console.v1.SignUpResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/console/auth/sign-up\x1a\x06\x92\xb2\x19\x02\b\x01B\xce\x02\x92A\x89\x02Z\xe6\x01\n" +
	"3\n" +
	"\x06Bearer\x12)\b\x02\x12\x14格式: Bearer <jwt>\x1a\rAuthorization \x02\n" +
	"\\\n" +
	"\x06apiKey\x12R\b\x02\x12AServer API key（需同时携带 X-Torchwood-Project 请求头）\x1a\tX-API-Key \x02\n" +
	"Q\n" +
	"\x06cookie\x12G\b\x02\x129TORCHWOOD_session_console=<sid>（Console admin 会话）\x1a\x06Cookie \x02z\x1e\n" +
	"\x12x-torchwood-access\x12\b\x1a\x06publicZ?github.com/torchwooddev/torchwood/genproto/console/v1;consolev1b\x06proto3"

var (
	file_console_v1_auth_proto_rawDescOnce sync.Once
	file_console_v1_auth_proto_rawDescData []byte
)

func file_console_v1_auth_proto_rawDescGZIP() []byte {
	file_console_v1_auth_proto_rawDescOnce.Do(func() {
		file_console_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_v1_auth_proto_rawDesc), len(file_console_v1_auth_proto_rawDesc)))
	})
	return file_console_v1_auth_proto_rawDescData
}

var file_console_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_console_v1_auth_proto_goTypes = []any{
	(*SignInRequest)(nil),          // 0: torchwood.console.v1.SignInRequest
	(*SignInResponse)(nil),         // 1: torchwood.console.v1.SignInResponse
	(*RefreshTokenRequest)(nil),    // 2: torchwood.console.v1.RefreshTokenRequest
	(*SignOutRequest)(nil),         // 3: torchwood.console.v1.SignOutRequest
	(*GetSetupStatusRequest)(nil),  // 4: torchwood.console.v1.GetSetupStatusRequest
	(*GetSetupStatusResponse)(nil), // 5: torchwood.console.v1.GetSetupStatusResponse
	(*SignUpRequest)(nil),          // 6: torchwood.console.v1.SignUpRequest
	(*SignUpResponse)(nil),         // 7: torchwood.console.v1.SignUpResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*Admin)(nil),                  // 9: torchwood.console.v1.Admin
	(*v1.Empty)(nil),               // 10: torchwood.shared.v1.Empty
}
var file_console_v1_auth_proto_depIdxs = []int32{
	8,  // 0: torchwood.console.v1.SignInResponse.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 1: torchwood.console.v1.SignUpResponse.admin:type_name -> torchwood.console.v1.Admin
	0,  // 2: torchwood.console.v1.ConsoleAuthService.SignIn:input_type -> torchwood.console.v1.SignInRequest
	2,  // 3: torchwood.console.v1.ConsoleAuthService.RefreshToken:input_type -> torchwood.console.v1.RefreshTokenRequest
	3,  // 4: torchwood.console.v1.ConsoleAuthService.SignOut:input_type -> torchwood.console.v1.SignOutRequest
	4,  // 5: torchwood.console.v1.ConsoleAuthService.GetSetupStatus:input_type -> torchwood.console.v1.GetSetupStatusRequest
	6,  // 6: torchwood.console.v1.ConsoleAuthService.SignUp:input_type -> torchwood.console.v1.SignUpRequest
	1,  // 7: torchwood.console.v1.ConsoleAuthService.SignIn:output_type -> torchwood.console.v1.SignInResponse
	1,  // 8: torchwood.console.v1.ConsoleAuthService.RefreshToken:output_type -> torchwood.console.v1.SignInResponse
	10, // 9: torchwood.console.v1.ConsoleAuthService.SignOut:output_type -> torchwood.shared.v1.Empty
	5,  // 10: torchwood.console.v1.ConsoleAuthService.GetSetupStatus:output_type -> torchwood.console.v1.GetSetupStatusResponse
	7,  // 11: torchwood.console.v1.ConsoleAuthService.SignUp:output_type -> torchwood.console.v1.SignUpResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_console_v1_auth_proto_init() }
func file_console_v1_auth_proto_init() {
	if File_console_v1_auth_proto != nil {
		return
	}
	file_console_v1_admins_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_v1_auth_proto_rawDesc), len(file_console_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_v1_auth_proto_goTypes,
		DependencyIndexes: file_console_v1_auth_proto_depIdxs,
		MessageInfos:      file_console_v1_auth_proto_msgTypes,
	}.Build()
	File_console_v1_auth_proto = out.File
	file_console_v1_auth_proto_goTypes = nil
	file_console_v1_auth_proto_depIdxs = nil
}
