// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: shared/v1/query.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Comparison is a leaf predicate: attribute plus one or more values.
type Comparison struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     string                 `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comparison) Reset() {
	*x = Comparison{}
	mi := &file_shared_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comparison) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comparison) ProtoMessage() {}

func (x *Comparison) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comparison.ProtoReflect.Descriptor instead.
func (*Comparison) Descriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *Comparison) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *Comparison) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// FilterList is a boolean combination of Filter nodes (and / or).
type FilterList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterList) Reset() {
	*x = FilterList{}
	mi := &file_shared_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterList) ProtoMessage() {}

func (x *FilterList) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterList.ProtoReflect.Descriptor instead.
func (*FilterList) Descriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *FilterList) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

// Filter is a boolean expression tree. Comparison ops use Appwrite-equivalent
// semantics; and/or are recursive. The Appwrite string codec remains implicit AND.
type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Expr:
	//
	//	*Filter_Eq
	//	*Filter_Ne
	//	*Filter_Lt
	//	*Filter_Lte
	//	*Filter_Gt
	//	*Filter_Gte
	//	*Filter_In
	//	*Filter_Contains
	//	*Filter_StartsWith
	//	*Filter_EndsWith
	//	*Filter_Search
	//	*Filter_And
	//	*Filter_Or
	Expr          isFilter_Expr `protobuf_oneof:"expr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_shared_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetExpr() isFilter_Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Filter) GetEq() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Eq); ok {
			return x.Eq
		}
	}
	return nil
}

func (x *Filter) GetNe() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Ne); ok {
			return x.Ne
		}
	}
	return nil
}

func (x *Filter) GetLt() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Lt); ok {
			return x.Lt
		}
	}
	return nil
}

func (x *Filter) GetLte() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Lte); ok {
			return x.Lte
		}
	}
	return nil
}

func (x *Filter) GetGt() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Gt); ok {
			return x.Gt
		}
	}
	return nil
}

func (x *Filter) GetGte() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Gte); ok {
			return x.Gte
		}
	}
	return nil
}

func (x *Filter) GetIn() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *Filter) GetContains() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Contains); ok {
			return x.Contains
		}
	}
	return nil
}

func (x *Filter) GetStartsWith() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_StartsWith); ok {
			return x.StartsWith
		}
	}
	return nil
}

func (x *Filter) GetEndsWith() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_EndsWith); ok {
			return x.EndsWith
		}
	}
	return nil
}

func (x *Filter) GetSearch() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Search); ok {
			return x.Search
		}
	}
	return nil
}

func (x *Filter) GetAnd() *FilterList {
	if x != nil {
		if x, ok := x.Expr.(*Filter_And); ok {
			return x.And
		}
	}
	return nil
}

func (x *Filter) GetOr() *FilterList {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Or); ok {
			return x.Or
		}
	}
	return nil
}

type isFilter_Expr interface {
	isFilter_Expr()
}

type Filter_Eq struct {
	Eq *Comparison `protobuf:"bytes,1,opt,name=eq,proto3,oneof"`
}

type Filter_Ne struct {
	Ne *Comparison `protobuf:"bytes,2,opt,name=ne,proto3,oneof"`
}

type Filter_Lt struct {
	Lt *Comparison `protobuf:"bytes,3,opt,name=lt,proto3,oneof"`
}

type Filter_Lte struct {
	Lte *Comparison `protobuf:"bytes,4,opt,name=lte,proto3,oneof"`
}

type Filter_Gt struct {
	Gt *Comparison `protobuf:"bytes,5,opt,name=gt,proto3,oneof"`
}

type Filter_Gte struct {
	Gte *Comparison `protobuf:"bytes,6,opt,name=gte,proto3,oneof"`
}

type Filter_In struct {
	In *Comparison `protobuf:"bytes,7,opt,name=in,proto3,oneof"`
}

type Filter_Contains struct {
	Contains *Comparison `protobuf:"bytes,8,opt,name=contains,proto3,oneof"`
}

type Filter_StartsWith struct {
	StartsWith *Comparison `protobuf:"bytes,9,opt,name=starts_with,json=startsWith,proto3,oneof"`
}

type Filter_EndsWith struct {
	EndsWith *Comparison `protobuf:"bytes,10,opt,name=ends_with,json=endsWith,proto3,oneof"`
}

type Filter_Search struct {
	Search *Comparison `protobuf:"bytes,11,opt,name=search,proto3,oneof"`
}

type Filter_And struct {
	And *FilterList `protobuf:"bytes,12,opt,name=and,proto3,oneof"`
}

type Filter_Or struct {
	Or *FilterList `protobuf:"bytes,13,opt,name=or,proto3,oneof"`
}

func (*Filter_Eq) isFilter_Expr() {}

func (*Filter_Ne) isFilter_Expr() {}

func (*Filter_Lt) isFilter_Expr() {}

func (*Filter_Lte) isFilter_Expr() {}

func (*Filter_Gt) isFilter_Expr() {}

func (*Filter_Gte) isFilter_Expr() {}

func (*Filter_In) isFilter_Expr() {}

func (*Filter_Contains) isFilter_Expr() {}

func (*Filter_StartsWith) isFilter_Expr() {}

func (*Filter_EndsWith) isFilter_Expr() {}

func (*Filter_Search) isFilter_Expr() {}

func (*Filter_And) isFilter_Expr() {}

func (*Filter_Or) isFilter_Expr() {}

// Order is a single sort key. desc=false is ascending.
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     string                 `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_shared_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *Order) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *Order) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

// Query is the typed document list/count model (filter tree + orders + page).
// page_token is the authoritative pager (K-20); page_size is the page bound.
type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_shared_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *Query) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *Query) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *Query) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Query) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

var File_shared_v1_query_proto protoreflect.FileDescriptor

const file_shared_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x15shared/v1/query.proto\x12\x13torchwood.shared.v1\"B\n" +
	"\n" +
	"Comparison\x12\x1c\n" +
	"\tattribute\x18\x01 \x01(\tR\tattribute\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"C\n" +
	"\n" +
	"FilterList\x125\n" +
	"\afilters\x18\x01 \x03(\v2\x1b.torchwood.shared.v1.FilterR\afilters\"\xdf\x05\n" +
	"\x06Filter\x121\n" +
	"\x02eq\x18\x01 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x02eq\x121\n" +
	"\x02ne\x18\x02 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x02ne\x121\n" +
	"\x02lt\x18\x03 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x02lt\x123\n" +
	"\x03lte\x18\x04 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x03lte\x121\n" +
	"\x02gt\x18\x05 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x02gt\x123\n" +
	"\x03gte\x18\x06 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x03gte\x121\n" +
	"\x02in\x18\a \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x02in\x12=\n" +
	"\bcontains\x18\b \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\bcontains\x12B\n" +
	"\vstarts_with\x18\t \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\n" +
	"startsWith\x12>\n" +
	"\tends_with\x18\n" +
	" \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\bendsWith\x129\n" +
	"\x06search\x18\v \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x06search\x123\n" +
	"\x03and\x18\f \x01(\v2\x1f.torchwood.shared.v1.FilterListH\x00R\x03and\x121\n" +
	"\x02or\x18\r \x01(\v2\x1f.torchwood.shared.v1.FilterListH\x00R\x02orB\x06\n" +
	"\x04expr\"9\n" +
	"\x05Order\x12\x1c\n" +
	"\tattribute\x18\x01 \x01(\tR\tattribute\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"\xac\x01\n" +
	"\x05Query\x123\n" +
	"\x06filter\x18\x01 \x01(\v2\x1b.torchwood.shared.v1.FilterR\x06filter\x122\n" +
	"\x06orders\x18\x02 \x03(\v2\x1a.torchwood.shared.v1.OrderR\x06orders\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageTokenB?Z=github.com/torchwooddev/torchwood/genproto/shared/v1;sharedv1b\x06proto3"

var (
	file_shared_v1_query_proto_rawDescOnce sync.Once
	file_shared_v1_query_proto_rawDescData []byte
)

func file_shared_v1_query_proto_rawDescGZIP() []byte {
	file_shared_v1_query_proto_rawDescOnce.Do(func() {
		file_shared_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_v1_query_proto_rawDesc), len(file_shared_v1_query_proto_rawDesc)))
	})
	return file_shared_v1_query_proto_rawDescData
}

var file_shared_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shared_v1_query_proto_goTypes = []any{
	(*Comparison)(nil), // 0: torchwood.shared.v1.Comparison
	(*FilterList)(nil), // 1: torchwood.shared.v1.FilterList
	(*Filter)(nil),     // 2: torchwood.shared.v1.Filter
	(*Order)(nil),      // 3: torchwood.shared.v1.Order
	(*Query)(nil),      // 4: torchwood.shared.v1.Query
}
var file_shared_v1_query_proto_depIdxs = []int32{
	2,  // 0: torchwood.shared.v1.FilterList.filters:type_name -> torchwood.shared.v1.Filter
	0,  // 1: torchwood.shared.v1.Filter.eq:type_name -> torchwood.shared.v1.Comparison
	0,  // 2: torchwood.shared.v1.Filter.ne:type_name -> torchwood.shared.v1.Comparison
	0,  // 3: torchwood.shared.v1.Filter.lt:type_name -> torchwood.shared.v1.Comparison
	0,  // 4: torchwood.shared.v1.Filter.lte:type_name -> torchwood.shared.v1.Comparison
	0,  // 5: torchwood.shared.v1.Filter.gt:type_name -> torchwood.shared.v1.Comparison
	0,  // 6: torchwood.shared.v1.Filter.gte:type_name -> torchwood.shared.v1.Comparison
	0,  // 7: torchwood.shared.v1.Filter.in:type_name -> torchwood.shared.v1.Comparison
	0,  // 8: torchwood.shared.v1.Filter.contains:type_name -> torchwood.shared.v1.Comparison
	0,  // 9: torchwood.shared.v1.Filter.starts_with:type_name -> torchwood.shared.v1.Comparison
	0,  // 10: torchwood.shared.v1.Filter.ends_with:type_name -> torchwood.shared.v1.Comparison
	0,  // 11: torchwood.shared.v1.Filter.search:type_name -> torchwood.shared.v1.Comparison
	1,  // 12: torchwood.shared.v1.Filter.and:type_name -> torchwood.shared.v1.FilterList
	1,  // 13: torchwood.shared.v1.Filter.or:type_name -> torchwood.shared.v1.FilterList
	2,  // 14: torchwood.shared.v1.Query.filter:type_name -> torchwood.shared.v1.Filter
	3,  // 15: torchwood.shared.v1.Query.orders:type_name -> torchwood.shared.v1.Order
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_shared_v1_query_proto_init() }
func file_shared_v1_query_proto_init() {
	if File_shared_v1_query_proto != nil {
		return
	}
	file_shared_v1_query_proto_msgTypes[2].OneofWrappers = []any{
		(*Filter_Eq)(nil),
		(*Filter_Ne)(nil),
		(*Filter_Lt)(nil),
		(*Filter_Lte)(nil),
		(*Filter_Gt)(nil),
		(*Filter_Gte)(nil),
		(*Filter_In)(nil),
		(*Filter_Contains)(nil),
		(*Filter_StartsWith)(nil),
		(*Filter_EndsWith)(nil),
		(*Filter_Search)(nil),
		(*Filter_And)(nil),
		(*Filter_Or)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_v1_query_proto_rawDesc), len(file_shared_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_v1_query_proto_goTypes,
		DependencyIndexes: file_shared_v1_query_proto_depIdxs,
		MessageInfos:      file_shared_v1_query_proto_msgTypes,
	}.Build()
	File_shared_v1_query_proto = out.File
	file_shared_v1_query_proto_goTypes = nil
	file_shared_v1_query_proto_depIdxs = nil
}
