// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: shared/v1/query.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DistanceMetric 是向量近邻查询的距离度量（会话 #10，与 hnsw 索引的
// distance_metric 同一枚举域）。
type DistanceMetric int32

const (
	DistanceMetric_DISTANCE_METRIC_UNSPECIFIED DistanceMetric = 0
	// 余弦距离（PG <=>，HNSW vector_cosine_ops）。缺省即 COSINE。
	DistanceMetric_DISTANCE_METRIC_COSINE DistanceMetric = 1
	// 欧氏距离（PG <->，HNSW vector_l2_ops）。
	DistanceMetric_DISTANCE_METRIC_L2 DistanceMetric = 2
	// 内积负值（PG <#>，HNSW vector_ip_ops；pgvector 以负内积为"距离"，
	// 值域 (-inf, 0]，越小越近）。
	DistanceMetric_DISTANCE_METRIC_INNER_PRODUCT DistanceMetric = 3
)

// Enum value maps for DistanceMetric.
var (
	DistanceMetric_name = map[int32]string{
		0: "DISTANCE_METRIC_UNSPECIFIED",
		1: "DISTANCE_METRIC_COSINE",
		2: "DISTANCE_METRIC_L2",
		3: "DISTANCE_METRIC_INNER_PRODUCT",
	}
	DistanceMetric_value = map[string]int32{
		"DISTANCE_METRIC_UNSPECIFIED":   0,
		"DISTANCE_METRIC_COSINE":        1,
		"DISTANCE_METRIC_L2":            2,
		"DISTANCE_METRIC_INNER_PRODUCT": 3,
	}
)

func (x DistanceMetric) Enum() *DistanceMetric {
	p := new(DistanceMetric)
	*p = x
	return p
}

func (x DistanceMetric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistanceMetric) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_v1_query_proto_enumTypes[0].Descriptor()
}

func (DistanceMetric) Type() protoreflect.EnumType {
	return &file_shared_v1_query_proto_enumTypes[0]
}

func (x DistanceMetric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistanceMetric.Descriptor instead.
func (DistanceMetric) EnumDescriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{0}
}

// VectorSearch 是向量近邻查询（会话 #10 §10.5 P0：KNN 一等算子）。
// 不是 filter 树节点：距离不可作布尔谓词——排序由距离承载，limit 即 k
// （top-k 可见近邻，iterative scan 语义：迭代搜索直至凑满 k 个满足全部
// 过滤条件的行）。values 须与目标 vector 属性 dims 等长。目标列必须
// 声明为 vector 属性且存在与 metric 匹配的 hnsw 索引（显式拒绝原则，
// 与 search 需 fulltext 索引同款纪律）。DSL 字符串不支持 vector_search
// （向量不该手写，SDK typed builder only）。
type VectorSearch struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Attribute string                 `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Values    []float64              `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	Metric    DistanceMetric         `protobuf:"varint,3,opt,name=metric,proto3,enum=torchwood.shared.v1.DistanceMetric" json:"metric,omitempty"`
	// 距离阈值：仅保留 top-k 中距离 <= max_distance 的行（服务端在 top-k
	// 结果上后置过滤——距离谓词进 WHERE 会使规划器放弃 HNSW 索引扫描，
	// 原型 2 实证）。缺省无阈值。
	MaxDistance   *float64 `protobuf:"fixed64,4,opt,name=max_distance,json=maxDistance,proto3,oneof" json:"max_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearch) Reset() {
	*x = VectorSearch{}
	mi := &file_shared_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearch) ProtoMessage() {}

func (x *VectorSearch) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearch.ProtoReflect.Descriptor instead.
func (*VectorSearch) Descriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *VectorSearch) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *VectorSearch) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *VectorSearch) GetMetric() DistanceMetric {
	if x != nil {
		return x.Metric
	}
	return DistanceMetric_DISTANCE_METRIC_UNSPECIFIED
}

func (x *VectorSearch) GetMaxDistance() float64 {
	if x != nil && x.MaxDistance != nil {
		return *x.MaxDistance
	}
	return 0
}

// Comparison is a leaf predicate: attribute plus zero or more values.
// Value arity per operator: eq/ne/lt/lte/gt/gte/in/contains/starts_with/
// ends_with/search >= 1; between/not_between exactly 2; is_null/is_not_null 0.
type Comparison struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     string                 `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comparison) Reset() {
	*x = Comparison{}
	mi := &file_shared_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comparison) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comparison) ProtoMessage() {}

func (x *Comparison) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comparison.ProtoReflect.Descriptor instead.
func (*Comparison) Descriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *Comparison) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *Comparison) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// FilterList is a boolean combination of Filter nodes (and / or).
type FilterList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterList) Reset() {
	*x = FilterList{}
	mi := &file_shared_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterList) ProtoMessage() {}

func (x *FilterList) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterList.ProtoReflect.Descriptor instead.
func (*FilterList) Descriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *FilterList) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

// Filter is a boolean expression tree (single-AST, C7). Comparison ops use
// Appwrite-equivalent semantics; and/or are recursive (depth <= 8). Negation
// is expressed by not* variants only (index-friendly); there is no generic
// NOT operator.
type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Expr:
	//
	//	*Filter_Eq
	//	*Filter_Ne
	//	*Filter_Lt
	//	*Filter_Lte
	//	*Filter_Gt
	//	*Filter_Gte
	//	*Filter_In
	//	*Filter_Contains
	//	*Filter_StartsWith
	//	*Filter_EndsWith
	//	*Filter_Search
	//	*Filter_And
	//	*Filter_Or
	//	*Filter_Between
	//	*Filter_IsNull
	//	*Filter_IsNotNull
	//	*Filter_NotBetween
	//	*Filter_NotContains
	//	*Filter_NotStartsWith
	//	*Filter_NotEndsWith
	//	*Filter_NotSearch
	//	*Filter_ContainsAny
	//	*Filter_ContainsAll
	Expr          isFilter_Expr `protobuf_oneof:"expr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_shared_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *Filter) GetExpr() isFilter_Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Filter) GetEq() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Eq); ok {
			return x.Eq
		}
	}
	return nil
}

func (x *Filter) GetNe() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Ne); ok {
			return x.Ne
		}
	}
	return nil
}

func (x *Filter) GetLt() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Lt); ok {
			return x.Lt
		}
	}
	return nil
}

func (x *Filter) GetLte() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Lte); ok {
			return x.Lte
		}
	}
	return nil
}

func (x *Filter) GetGt() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Gt); ok {
			return x.Gt
		}
	}
	return nil
}

func (x *Filter) GetGte() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Gte); ok {
			return x.Gte
		}
	}
	return nil
}

func (x *Filter) GetIn() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *Filter) GetContains() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Contains); ok {
			return x.Contains
		}
	}
	return nil
}

func (x *Filter) GetStartsWith() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_StartsWith); ok {
			return x.StartsWith
		}
	}
	return nil
}

func (x *Filter) GetEndsWith() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_EndsWith); ok {
			return x.EndsWith
		}
	}
	return nil
}

func (x *Filter) GetSearch() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Search); ok {
			return x.Search
		}
	}
	return nil
}

func (x *Filter) GetAnd() *FilterList {
	if x != nil {
		if x, ok := x.Expr.(*Filter_And); ok {
			return x.And
		}
	}
	return nil
}

func (x *Filter) GetOr() *FilterList {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Or); ok {
			return x.Or
		}
	}
	return nil
}

func (x *Filter) GetBetween() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_Between); ok {
			return x.Between
		}
	}
	return nil
}

func (x *Filter) GetIsNull() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_IsNull); ok {
			return x.IsNull
		}
	}
	return nil
}

func (x *Filter) GetIsNotNull() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_IsNotNull); ok {
			return x.IsNotNull
		}
	}
	return nil
}

func (x *Filter) GetNotBetween() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_NotBetween); ok {
			return x.NotBetween
		}
	}
	return nil
}

func (x *Filter) GetNotContains() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_NotContains); ok {
			return x.NotContains
		}
	}
	return nil
}

func (x *Filter) GetNotStartsWith() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_NotStartsWith); ok {
			return x.NotStartsWith
		}
	}
	return nil
}

func (x *Filter) GetNotEndsWith() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_NotEndsWith); ok {
			return x.NotEndsWith
		}
	}
	return nil
}

func (x *Filter) GetNotSearch() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_NotSearch); ok {
			return x.NotSearch
		}
	}
	return nil
}

func (x *Filter) GetContainsAny() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_ContainsAny); ok {
			return x.ContainsAny
		}
	}
	return nil
}

func (x *Filter) GetContainsAll() *Comparison {
	if x != nil {
		if x, ok := x.Expr.(*Filter_ContainsAll); ok {
			return x.ContainsAll
		}
	}
	return nil
}

type isFilter_Expr interface {
	isFilter_Expr()
}

type Filter_Eq struct {
	Eq *Comparison `protobuf:"bytes,1,opt,name=eq,proto3,oneof"`
}

type Filter_Ne struct {
	Ne *Comparison `protobuf:"bytes,2,opt,name=ne,proto3,oneof"`
}

type Filter_Lt struct {
	Lt *Comparison `protobuf:"bytes,3,opt,name=lt,proto3,oneof"`
}

type Filter_Lte struct {
	Lte *Comparison `protobuf:"bytes,4,opt,name=lte,proto3,oneof"`
}

type Filter_Gt struct {
	Gt *Comparison `protobuf:"bytes,5,opt,name=gt,proto3,oneof"`
}

type Filter_Gte struct {
	Gte *Comparison `protobuf:"bytes,6,opt,name=gte,proto3,oneof"`
}

type Filter_In struct {
	In *Comparison `protobuf:"bytes,7,opt,name=in,proto3,oneof"`
}

type Filter_Contains struct {
	Contains *Comparison `protobuf:"bytes,8,opt,name=contains,proto3,oneof"`
}

type Filter_StartsWith struct {
	StartsWith *Comparison `protobuf:"bytes,9,opt,name=starts_with,json=startsWith,proto3,oneof"`
}

type Filter_EndsWith struct {
	EndsWith *Comparison `protobuf:"bytes,10,opt,name=ends_with,json=endsWith,proto3,oneof"`
}

type Filter_Search struct {
	Search *Comparison `protobuf:"bytes,11,opt,name=search,proto3,oneof"`
}

type Filter_And struct {
	And *FilterList `protobuf:"bytes,12,opt,name=and,proto3,oneof"`
}

type Filter_Or struct {
	Or *FilterList `protobuf:"bytes,13,opt,name=or,proto3,oneof"`
}

type Filter_Between struct {
	Between *Comparison `protobuf:"bytes,14,opt,name=between,proto3,oneof"`
}

type Filter_IsNull struct {
	IsNull *Comparison `protobuf:"bytes,15,opt,name=is_null,json=isNull,proto3,oneof"`
}

type Filter_IsNotNull struct {
	IsNotNull *Comparison `protobuf:"bytes,16,opt,name=is_not_null,json=isNotNull,proto3,oneof"`
}

type Filter_NotBetween struct {
	NotBetween *Comparison `protobuf:"bytes,17,opt,name=not_between,json=notBetween,proto3,oneof"`
}

type Filter_NotContains struct {
	NotContains *Comparison `protobuf:"bytes,18,opt,name=not_contains,json=notContains,proto3,oneof"`
}

type Filter_NotStartsWith struct {
	NotStartsWith *Comparison `protobuf:"bytes,19,opt,name=not_starts_with,json=notStartsWith,proto3,oneof"`
}

type Filter_NotEndsWith struct {
	NotEndsWith *Comparison `protobuf:"bytes,20,opt,name=not_ends_with,json=notEndsWith,proto3,oneof"`
}

type Filter_NotSearch struct {
	NotSearch *Comparison `protobuf:"bytes,21,opt,name=not_search,json=notSearch,proto3,oneof"`
}

type Filter_ContainsAny struct {
	// 数组算子（§10.5 P0）：仅 array=true 属性可用，服务端白名单校验。
	// contains_any 语义 = 交集非空（PG &&）；contains_all 语义 = 子集（PG @>）。
	ContainsAny *Comparison `protobuf:"bytes,22,opt,name=contains_any,json=containsAny,proto3,oneof"`
}

type Filter_ContainsAll struct {
	ContainsAll *Comparison `protobuf:"bytes,23,opt,name=contains_all,json=containsAll,proto3,oneof"`
}

func (*Filter_Eq) isFilter_Expr() {}

func (*Filter_Ne) isFilter_Expr() {}

func (*Filter_Lt) isFilter_Expr() {}

func (*Filter_Lte) isFilter_Expr() {}

func (*Filter_Gt) isFilter_Expr() {}

func (*Filter_Gte) isFilter_Expr() {}

func (*Filter_In) isFilter_Expr() {}

func (*Filter_Contains) isFilter_Expr() {}

func (*Filter_StartsWith) isFilter_Expr() {}

func (*Filter_EndsWith) isFilter_Expr() {}

func (*Filter_Search) isFilter_Expr() {}

func (*Filter_And) isFilter_Expr() {}

func (*Filter_Or) isFilter_Expr() {}

func (*Filter_Between) isFilter_Expr() {}

func (*Filter_IsNull) isFilter_Expr() {}

func (*Filter_IsNotNull) isFilter_Expr() {}

func (*Filter_NotBetween) isFilter_Expr() {}

func (*Filter_NotContains) isFilter_Expr() {}

func (*Filter_NotStartsWith) isFilter_Expr() {}

func (*Filter_NotEndsWith) isFilter_Expr() {}

func (*Filter_NotSearch) isFilter_Expr() {}

func (*Filter_ContainsAny) isFilter_Expr() {}

func (*Filter_ContainsAll) isFilter_Expr() {}

// Order is a single sort key. desc=false is ascending.
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     string                 `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_shared_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *Order) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

// Query is the single wire form of document list/count/aggregate filters
// (C7: the server consumes no query strings; the Appwrite DSL survives only
// as client-side sugar in SDKs/tools). page_token is the authoritative pager
// (K-20); page_size is the page bound.
// vector_search（会话 #10）：KNN 一次一个；与 filter 可组合（AND），与
// orders/page_token 互斥（排序由距离承载；多页 KNN 挂账）——服务端显式
// 拒绝非法组合，字段本身保留。
type Query struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Filter    *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Orders    []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	PageSize  int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Projection: server trims the returned Data to these fields.
	Select []string `protobuf:"bytes,5,rep,name=select,proto3" json:"select,omitempty"`
	// KNN 算子（会话 #10）：非 filter 节点，见 VectorSearch。
	VectorSearch  *VectorSearch `protobuf:"bytes,6,opt,name=vector_search,json=vectorSearch,proto3" json:"vector_search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_shared_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_shared_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_shared_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *Query) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *Query) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *Query) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Query) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *Query) GetSelect() []string {
	if x != nil {
		return x.Select
	}
	return nil
}

func (x *Query) GetVectorSearch() *VectorSearch {
	if x != nil {
		return x.VectorSearch
	}
	return nil
}

var File_shared_v1_query_proto protoreflect.FileDescriptor

const file_shared_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x15shared/v1/query.proto\x12\x13torchwood.shared.v1\"\xba\x01\n" +
	"\fVectorSearch\x12\x1c\n" +
	"\tattribute\x18\x01 \x01(\tR\tattribute\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x01R\x06values\x12;\n" +
	"\x06metric\x18\x03 \x01(\x0e2#.torchwood.shared.v1.DistanceMetricR\x06metric\x12&\n" +
	"\fmax_distance\x18\x04 \x01(\x01H\x00R\vmaxDistance\x88\x01\x01B\x0f\n" +
	"\r_max_distance\"B\n" +
	"\n" +
	"Comparison\x12\x1c\n" +
	"\tattribute\x18\x01 \x01(\tR\tattribute\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"C\n" +
	"\n" +
	"FilterList\x125\n" +
	"\afilters\x18\x01 \x03(\v2\x1b.torchwood.shared.v1.FilterR\afilters\"\x85\v\n" +
	"\x06Filter\x121\n" +
	"\x02eq\x18\x01 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x02eq\x121\n" +
	"\x02ne\x18\x02 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x02ne\x121\n" +
	"\x02lt\x18\x03 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x02lt\x123\n" +
	"\x03lte\x18\x04 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x03lte\x121\n" +
	"\x02gt\x18\x05 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x02gt\x123\n" +
	"\x03gte\x18\x06 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x03gte\x121\n" +
	"\x02in\x18\a \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x02in\x12=\n" +
	"\bcontains\x18\b \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\bcontains\x12B\n" +
	"\vstarts_with\x18\t \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\n" +
	"startsWith\x12>\n" +
	"\tends_with\x18\n" +
	" \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\bendsWith\x129\n" +
	"\x06search\x18\v \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x06search\x123\n" +
	"\x03and\x18\f \x01(\v2\x1f.torchwood.shared.v1.FilterListH\x00R\x03and\x121\n" +
	"\x02or\x18\r \x01(\v2\x1f.torchwood.shared.v1.FilterListH\x00R\x02or\x12;\n" +
	"\abetween\x18\x0e \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\abetween\x12:\n" +
	"\ais_null\x18\x0f \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\x06isNull\x12A\n" +
	"\vis_not_null\x18\x10 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\tisNotNull\x12B\n" +
	"\vnot_between\x18\x11 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\n" +
	"notBetween\x12D\n" +
	"\fnot_contains\x18\x12 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\vnotContains\x12I\n" +
	"\x0fnot_starts_with\x18\x13 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\rnotStartsWith\x12E\n" +
	"\rnot_ends_with\x18\x14 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\vnotEndsWith\x12@\n" +
	"\n" +
	"not_search\x18\x15 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\tnotSearch\x12D\n" +
	"\fcontains_any\x18\x16 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\vcontainsAny\x12D\n" +
	"\fcontains_all\x18\x17 \x01(\v2\x1f.torchwood.shared.v1.ComparisonH\x00R\vcontainsAllB\x06\n" +
	"\x04expr\"9\n" +
	"\x05Order\x12\x1c\n" +
	"\tattribute\x18\x01 \x01(\tR\tattribute\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"\x8c\x02\n" +
	"\x05Query\x123\n" +
	"\x06filter\x18\x01 \x01(\v2\x1b.torchwood.shared.v1.FilterR\x06filter\x122\n" +
	"\x06orders\x18\x02 \x03(\v2\x1a.torchwood.shared.v1.OrderR\x06orders\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06select\x18\x05 \x03(\tR\x06select\x12F\n" +
	"\rvector_search\x18\x06 \x01(\v2!.torchwood.shared.v1.VectorSearchR\fvectorSearch*\x88\x01\n" +
	"\x0eDistanceMetric\x12\x1f\n" +
	"\x1bDISTANCE_METRIC_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DISTANCE_METRIC_COSINE\x10\x01\x12\x16\n" +
	"\x12DISTANCE_METRIC_L2\x10\x02\x12!\n" +
	"\x1dDISTANCE_METRIC_INNER_PRODUCT\x10\x03B?Z=github.com/torchwooddev/torchwood/genproto/shared/v1;sharedv1b\x06proto3"

var (
	file_shared_v1_query_proto_rawDescOnce sync.Once
	file_shared_v1_query_proto_rawDescData []byte
)

func file_shared_v1_query_proto_rawDescGZIP() []byte {
	file_shared_v1_query_proto_rawDescOnce.Do(func() {
		file_shared_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_v1_query_proto_rawDesc), len(file_shared_v1_query_proto_rawDesc)))
	})
	return file_shared_v1_query_proto_rawDescData
}

var file_shared_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_v1_query_proto_goTypes = []any{
	(DistanceMetric)(0),  // 0: torchwood.shared.v1.DistanceMetric
	(*VectorSearch)(nil), // 1: torchwood.shared.v1.VectorSearch
	(*Comparison)(nil),   // 2: torchwood.shared.v1.Comparison
	(*FilterList)(nil),   // 3: torchwood.shared.v1.FilterList
	(*Filter)(nil),       // 4: torchwood.shared.v1.Filter
	(*Order)(nil),        // 5: torchwood.shared.v1.Order
	(*Query)(nil),        // 6: torchwood.shared.v1.Query
}
var file_shared_v1_query_proto_depIdxs = []int32{
	0,  // 0: torchwood.shared.v1.VectorSearch.metric:type_name -> torchwood.shared.v1.DistanceMetric
	4,  // 1: torchwood.shared.v1.FilterList.filters:type_name -> torchwood.shared.v1.Filter
	2,  // 2: torchwood.shared.v1.Filter.eq:type_name -> torchwood.shared.v1.Comparison
	2,  // 3: torchwood.shared.v1.Filter.ne:type_name -> torchwood.shared.v1.Comparison
	2,  // 4: torchwood.shared.v1.Filter.lt:type_name -> torchwood.shared.v1.Comparison
	2,  // 5: torchwood.shared.v1.Filter.lte:type_name -> torchwood.shared.v1.Comparison
	2,  // 6: torchwood.shared.v1.Filter.gt:type_name -> torchwood.shared.v1.Comparison
	2,  // 7: torchwood.shared.v1.Filter.gte:type_name -> torchwood.shared.v1.Comparison
	2,  // 8: torchwood.shared.v1.Filter.in:type_name -> torchwood.shared.v1.Comparison
	2,  // 9: torchwood.shared.v1.Filter.contains:type_name -> torchwood.shared.v1.Comparison
	2,  // 10: torchwood.shared.v1.Filter.starts_with:type_name -> torchwood.shared.v1.Comparison
	2,  // 11: torchwood.shared.v1.Filter.ends_with:type_name -> torchwood.shared.v1.Comparison
	2,  // 12: torchwood.shared.v1.Filter.search:type_name -> torchwood.shared.v1.Comparison
	3,  // 13: torchwood.shared.v1.Filter.and:type_name -> torchwood.shared.v1.FilterList
	3,  // 14: torchwood.shared.v1.Filter.or:type_name -> torchwood.shared.v1.FilterList
	2,  // 15: torchwood.shared.v1.Filter.between:type_name -> torchwood.shared.v1.Comparison
	2,  // 16: torchwood.shared.v1.Filter.is_null:type_name -> torchwood.shared.v1.Comparison
	2,  // 17: torchwood.shared.v1.Filter.is_not_null:type_name -> torchwood.shared.v1.Comparison
	2,  // 18: torchwood.shared.v1.Filter.not_between:type_name -> torchwood.shared.v1.Comparison
	2,  // 19: torchwood.shared.v1.Filter.not_contains:type_name -> torchwood.shared.v1.Comparison
	2,  // 20: torchwood.shared.v1.Filter.not_starts_with:type_name -> torchwood.shared.v1.Comparison
	2,  // 21: torchwood.shared.v1.Filter.not_ends_with:type_name -> torchwood.shared.v1.Comparison
	2,  // 22: torchwood.shared.v1.Filter.not_search:type_name -> torchwood.shared.v1.Comparison
	2,  // 23: torchwood.shared.v1.Filter.contains_any:type_name -> torchwood.shared.v1.Comparison
	2,  // 24: torchwood.shared.v1.Filter.contains_all:type_name -> torchwood.shared.v1.Comparison
	4,  // 25: torchwood.shared.v1.Query.filter:type_name -> torchwood.shared.v1.Filter
	5,  // 26: torchwood.shared.v1.Query.orders:type_name -> torchwood.shared.v1.Order
	1,  // 27: torchwood.shared.v1.Query.vector_search:type_name -> torchwood.shared.v1.VectorSearch
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_shared_v1_query_proto_init() }
func file_shared_v1_query_proto_init() {
	if File_shared_v1_query_proto != nil {
		return
	}
	file_shared_v1_query_proto_msgTypes[0].OneofWrappers = []any{}
	file_shared_v1_query_proto_msgTypes[3].OneofWrappers = []any{
		(*Filter_Eq)(nil),
		(*Filter_Ne)(nil),
		(*Filter_Lt)(nil),
		(*Filter_Lte)(nil),
		(*Filter_Gt)(nil),
		(*Filter_Gte)(nil),
		(*Filter_In)(nil),
		(*Filter_Contains)(nil),
		(*Filter_StartsWith)(nil),
		(*Filter_EndsWith)(nil),
		(*Filter_Search)(nil),
		(*Filter_And)(nil),
		(*Filter_Or)(nil),
		(*Filter_Between)(nil),
		(*Filter_IsNull)(nil),
		(*Filter_IsNotNull)(nil),
		(*Filter_NotBetween)(nil),
		(*Filter_NotContains)(nil),
		(*Filter_NotStartsWith)(nil),
		(*Filter_NotEndsWith)(nil),
		(*Filter_NotSearch)(nil),
		(*Filter_ContainsAny)(nil),
		(*Filter_ContainsAll)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_v1_query_proto_rawDesc), len(file_shared_v1_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_v1_query_proto_goTypes,
		DependencyIndexes: file_shared_v1_query_proto_depIdxs,
		EnumInfos:         file_shared_v1_query_proto_enumTypes,
		MessageInfos:      file_shared_v1_query_proto_msgTypes,
	}.Build()
	File_shared_v1_query_proto = out.File
	file_shared_v1_query_proto_goTypes = nil
	file_shared_v1_query_proto_depIdxs = nil
}
