syntax = "proto3";

package torchwood.client.v1;

option go_package = "github.com/torchwooddev/torchwood/genproto/client/v1;clientv1";

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "shared/v1/authz.proto";
import "shared/v1/common.proto";

service DatabasesService {
  option (torchwood.shared.v1.service_auth) = { default_access: ACCESS_AUTHENTICATED };

  rpc CreateDocument(CreateDocumentRequest) returns (Document) {
    option (google.api.http) = { post: "/v1/databases/{database_id}/collections/{collection_id}/documents", body: "*" };
  }

  rpc ListDocuments(ListDocumentsRequest) returns (ListDocumentsResponse) {
    option (google.api.http) = { get: "/v1/databases/{database_id}/collections/{collection_id}/documents" };
    option (torchwood.shared.v1.method_auth) = { access: ACCESS_PUBLIC };
  }

  rpc GetDocument(GetDocumentRequest) returns (Document) {
    option (google.api.http) = { get: "/v1/databases/{database_id}/collections/{collection_id}/documents/{document_id}" };
    option (torchwood.shared.v1.method_auth) = { access: ACCESS_PUBLIC };
  }

  rpc UpdateDocument(UpdateDocumentRequest) returns (Document) {
    option (google.api.http) = { patch: "/v1/databases/{database_id}/collections/{collection_id}/documents/{document_id}", body: "*" };
  }

  rpc UpsertDocument(UpsertDocumentRequest) returns (Document) {
    option (google.api.http) = { put: "/v1/databases/{database_id}/collections/{collection_id}/documents/{document_id}", body: "*" };
  }

  rpc DeleteDocument(GetDocumentRequest) returns (shared.v1.Empty) {
    option (google.api.http) = { delete: "/v1/databases/{database_id}/collections/{collection_id}/documents/{document_id}" };
  }

  rpc CountDocuments(ListDocumentsRequest) returns (CountDocumentsResponse) {
    option (google.api.http) = { get: "/v1/databases/{database_id}/collections/{collection_id}/documents/count" };
    option (torchwood.shared.v1.method_auth) = { access: ACCESS_PUBLIC };
  }
}

message Document {
  string id = 1;
  google.protobuf.Struct data = 2;
  google.protobuf.Timestamp created_at = 3;
  google.protobuf.Timestamp updated_at = 4;
  repeated string permissions = 5;
}

message CreateDocumentRequest {
  string database_id = 1;
  string collection_id = 2;
  string document_id = 3;
  google.protobuf.Struct data = 4;
  repeated string permissions = 5;
}

message UpdateDocumentRequest {
  string database_id = 1;
  string collection_id = 2;
  string document_id = 3;
  google.protobuf.Struct data = 4;
  repeated string permissions = 5;
  map<string, int64> increment = 6;
}

message UpsertDocumentRequest {
  string database_id = 1;
  string collection_id = 2;
  string document_id = 3;
  google.protobuf.Struct data = 4;
  repeated string permissions = 5;
  repeated string conflict_columns = 6;
}

message GetDocumentRequest {
  string database_id = 1;
  string collection_id = 2;
  string document_id = 3;
  string project_id = 4;
}

message ListDocumentsRequest {
  string database_id = 1;
  string collection_id = 2;
  repeated string queries = 3;
  int32 page_size = 4;
  string page_token = 5;
  string project_id = 6;
}

message ListDocumentsResponse {
  repeated Document documents = 1;
  shared.v1.ListResponseMeta meta = 2;
}

message CountDocumentsResponse {
  int64 count = 1;
}
