syntax = "proto3";

package torchwood.client.v1;

option go_package = "github.com/torchwoodio/torchwood/genproto/client/v1;clientv1";

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "shared/v1/authz.proto";
import "shared/v1/common.proto";

service TeamsService {
  option (torchwood.shared.v1.service_auth) = { default_access: ACCESS_AUTHENTICATED };

  rpc CreateTeam(CreateTeamRequest) returns (Team) {
    option (google.api.http) = { post: "/v1/teams", body: "*" };
  }

  rpc ListTeams(shared.v1.ListRequest) returns (ListTeamsResponse) {
    option (google.api.http) = { get: "/v1/teams" };
  }

  rpc GetTeam(GetTeamRequest) returns (Team) {
    option (google.api.http) = { get: "/v1/teams/{id}" };
  }

  rpc DeleteTeam(GetTeamRequest) returns (shared.v1.Empty) {
    option (google.api.http) = { delete: "/v1/teams/{id}" };
  }

  rpc CreateMembership(CreateMembershipRequest) returns (Membership) {
    option (google.api.http) = { post: "/v1/teams/{team_id}/memberships", body: "*" };
  }

  rpc ListMemberships(ListMembershipsRequest) returns (ListMembershipsResponse) {
    option (google.api.http) = { get: "/v1/teams/{team_id}/memberships" };
  }

  rpc UpdateMembershipStatus(UpdateMembershipStatusRequest) returns (Membership) {
    option (google.api.http) = { patch: "/v1/teams/{team_id}/memberships/{membership_id}/status", body: "*" };
  }

  rpc DeleteMembership(GetMembershipRequest) returns (shared.v1.Empty) {
    option (google.api.http) = { delete: "/v1/teams/{team_id}/memberships/{membership_id}" };
  }
}

message CreateTeamRequest {
  string name = 1;
}

message GetTeamRequest {
  string id = 1;
}

message ListTeamsResponse {
  repeated Team teams = 1;
  shared.v1.ListResponseMeta meta = 2;
}

message Team {
  string id = 1;
  string name = 2;
  int32 total = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
}

message Membership {
  string id = 1;
  string team_id = 2;
  string user_id = 3;
  string email = 4;
  string name = 5;
  repeated string roles = 6;
  string status = 7;
  google.protobuf.Timestamp invited_at = 8;
  google.protobuf.Timestamp joined_at = 9;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
}

message CreateMembershipRequest {
  string team_id = 1;
  string email = 2;
  string name = 3;
  repeated string roles = 4;
}

message ListMembershipsRequest {
  string team_id = 1;
}

message GetMembershipRequest {
  string team_id = 1;
  string membership_id = 2;
}

message ListMembershipsResponse {
  repeated Membership memberships = 1;
}

message UpdateMembershipStatusRequest {
  string team_id = 1;
  string membership_id = 2;
  string status = 3;
}
