// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx/boot"
	"github.com/torchwoodio/torchwood/internal/api/clientgrpc"
	"github.com/torchwoodio/torchwood/internal/api/consolegrpc"
	"github.com/torchwoodio/torchwood/internal/api/servergrpc"
	"github.com/torchwoodio/torchwood/internal/api/serverhttp"
	"github.com/torchwoodio/torchwood/internal/app/client"
	"github.com/torchwoodio/torchwood/internal/app/console"
	"github.com/torchwoodio/torchwood/internal/app/server"
	storage2 "github.com/torchwoodio/torchwood/internal/app/storage"
	"github.com/torchwoodio/torchwood/internal/infra/auth"
	"github.com/torchwoodio/torchwood/internal/infra/bun/bunrepo"
	"github.com/torchwoodio/torchwood/internal/infra/clients"
	"github.com/torchwoodio/torchwood/internal/infra/documentdb"
	"github.com/torchwoodio/torchwood/internal/infra/idgen"
	"github.com/torchwoodio/torchwood/internal/infra/messaging"
	server2 "github.com/torchwoodio/torchwood/internal/infra/server"
	"github.com/torchwoodio/torchwood/internal/infra/storage"
)

// Injectors from wire.go:

func wireBootstrap(app lynx.Lynx) (*boot.Bootstrap, func(), error) {
	onStartHooks := NewOnStarts()
	onStopHooks := NewOnStops()
	appConfig, err := NewAppConfig(app)
	if err != nil {
		return nil, nil, err
	}
	dataClients, cleanup, err := clients.NewDataClients(appConfig)
	if err != nil {
		return nil, nil, err
	}
	database := clients.NewDatabase(dataClients)
	apiKeyRepository := bunrepo.NewAPIKeyRepository(database)
	consoleAdminRepository := bunrepo.NewConsoleAdminRepository(database)
	consoleAdminProjectRepository := bunrepo.NewConsoleAdminProjectRepository(database)
	redisClient := clients.NewRedis(dataClients)
	redisAdminTokenRevokeStore := auth.NewRedisAdminTokenRevokeStore(redisClient)
	documentDB := documentdb.NewPostgresDocumentDB(database)
	validator := auth.NewValidator(appConfig, apiKeyRepository, consoleAdminRepository, consoleAdminProjectRepository, redisAdminTokenRevokeStore, documentDB)
	repository := bunrepo.NewAuditRepository(database)
	projectsRepository := bunrepo.NewProjectRepository(database)
	oAuthProviderRepository := bunrepo.NewOAuthProviderRepository(database, appConfig)
	userRoles := client.NewUserRoles(documentDB)
	redisRefreshRotationStore := auth.NewRedisRefreshRotationStore(redisClient)
	sessionService := auth.NewSessionService(appConfig, documentDB, userRoles, redisRefreshRotationStore)
	redisOTPChallengeStore := auth.NewRedisOTPChallengeStore(redisClient, appConfig)
	redisOAuthStateStore := auth.NewRedisOAuthStateStore(redisClient)
	redisAccountTokenStore := auth.NewRedisAccountTokenStore(redisClient)
	redisLoginThrottle := auth.NewRedisLoginThrottle(redisClient)
	service, err := idgen.NewService(appConfig, redisClient, projectsRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mailerService := messaging.NewMailer(appConfig)
	smsService := messaging.NewSMSService(appConfig)
	redisRateLimiter := auth.NewRedisRateLimiter(redisClient)
	account := client.NewAccount(appConfig, projectsRepository, oAuthProviderRepository, documentDB, sessionService, redisOTPChallengeStore, redisOAuthStateStore, redisAccountTokenStore, redisLoginThrottle, redisRefreshRotationStore, service, mailerService, smsService, redisRateLimiter)
	accountService := clientgrpc.NewAccountService(account)
	databases := client.NewDatabases(projectsRepository, documentDB)
	databasesService := clientgrpc.NewDatabasesService(databases)
	teams := server.NewTeams(projectsRepository, documentDB)
	clientTeams := client.NewTeams(teams)
	teamsService := clientgrpc.NewTeamsService(clientTeams)
	healthService := servergrpc.NewHealthService()
	projects := server.NewProjects(projectsRepository, documentDB, database)
	projectsService := servergrpc.NewProjectsService(projects)
	objectStore, err := storage.NewMinioObjectStore(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	storageStorage := storage2.NewStorage(appConfig, projectsRepository, documentDB, objectStore)
	storageService := servergrpc.NewStorageService(storageStorage)
	users := server.NewUsers(projectsRepository, documentDB)
	usersService := servergrpc.NewUsersService(users)
	apiKeys := server.NewAPIKeys(apiKeyRepository)
	apiKeysService := servergrpc.NewAPIKeysService(apiKeys)
	oAuthProviders := server.NewOAuthProviders(oAuthProviderRepository)
	oAuthProvidersService := servergrpc.NewOAuthProvidersService(oAuthProviders)
	servergrpcTeamsService := servergrpc.NewTeamsService(teams)
	serverDatabases := server.NewDatabases(projectsRepository, documentDB)
	servergrpcDatabasesService := servergrpc.NewDatabasesService(serverDatabases)
	consoleAuth := console.NewAuth(appConfig, consoleAdminRepository, redisAdminTokenRevokeStore, redisLoginThrottle, redisRefreshRotationStore)
	authService := consolegrpc.NewAuthService(consoleAuth)
	grpcServer, err := server2.NewGRPCServer(app, appConfig, validator, repository, accountService, databasesService, teamsService, healthService, projectsService, storageService, usersService, apiKeysService, oAuthProvidersService, servergrpcTeamsService, servergrpcDatabasesService, authService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	fileHandler, err := serverhttp.NewFileHandler(appConfig, validator, storageStorage)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	oAuthHandler, err := serverhttp.NewOAuthHandler(account, appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcGatewayServer, err := server2.NewGRPCGatewayServer(app, appConfig, fileHandler, oAuthHandler)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	metricsServer, err := server2.NewMetricsServer(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	v := NewComponents(grpcServer, grpcGatewayServer, metricsServer)
	v2 := NewComponentBuilders()
	componentBuilderSetFunc := NewComponentBuilderSetFunc()
	bootstrap := boot.New(onStartHooks, onStopHooks, v, v2, componentBuilderSetFunc)
	return bootstrap, func() {
		cleanup()
	}, nil
}
