// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: client/v1/assets.proto

package clientv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetsService_ListAssetDefs_FullMethodName     = "/torchwood.client.v1.AssetsService/ListAssetDefs"
	AssetsService_ListMyAssets_FullMethodName      = "/torchwood.client.v1.AssetsService/ListMyAssets"
	AssetsService_ListMyAssetLedger_FullMethodName = "/torchwood.client.v1.AssetsService/ListMyAssetLedger"
)

// AssetsServiceClient is the client API for AssetsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AssetsService 是终端用户资产面（v3 设计 §2.7 / §6）：只读三个方法。
// 终端用户没有任何直接写资产的 API（红线 D6）。
type AssetsServiceClient interface {
	ListAssetDefs(ctx context.Context, in *ListAssetDefsRequest, opts ...grpc.CallOption) (*ListAssetDefsResponse, error)
	ListMyAssets(ctx context.Context, in *ListMyAssetsRequest, opts ...grpc.CallOption) (*ListMyAssetsResponse, error)
	ListMyAssetLedger(ctx context.Context, in *ListMyAssetLedgerRequest, opts ...grpc.CallOption) (*ListMyAssetLedgerResponse, error)
}

type assetsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetsServiceClient(cc grpc.ClientConnInterface) AssetsServiceClient {
	return &assetsServiceClient{cc}
}

func (c *assetsServiceClient) ListAssetDefs(ctx context.Context, in *ListAssetDefsRequest, opts ...grpc.CallOption) (*ListAssetDefsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssetDefsResponse)
	err := c.cc.Invoke(ctx, AssetsService_ListAssetDefs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) ListMyAssets(ctx context.Context, in *ListMyAssetsRequest, opts ...grpc.CallOption) (*ListMyAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyAssetsResponse)
	err := c.cc.Invoke(ctx, AssetsService_ListMyAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) ListMyAssetLedger(ctx context.Context, in *ListMyAssetLedgerRequest, opts ...grpc.CallOption) (*ListMyAssetLedgerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyAssetLedgerResponse)
	err := c.cc.Invoke(ctx, AssetsService_ListMyAssetLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetsServiceServer is the server API for AssetsService service.
// All implementations must embed UnimplementedAssetsServiceServer
// for forward compatibility.
//
// AssetsService 是终端用户资产面（v3 设计 §2.7 / §6）：只读三个方法。
// 终端用户没有任何直接写资产的 API（红线 D6）。
type AssetsServiceServer interface {
	ListAssetDefs(context.Context, *ListAssetDefsRequest) (*ListAssetDefsResponse, error)
	ListMyAssets(context.Context, *ListMyAssetsRequest) (*ListMyAssetsResponse, error)
	ListMyAssetLedger(context.Context, *ListMyAssetLedgerRequest) (*ListMyAssetLedgerResponse, error)
	mustEmbedUnimplementedAssetsServiceServer()
}

// UnimplementedAssetsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetsServiceServer struct{}

func (UnimplementedAssetsServiceServer) ListAssetDefs(context.Context, *ListAssetDefsRequest) (*ListAssetDefsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssetDefs not implemented")
}
func (UnimplementedAssetsServiceServer) ListMyAssets(context.Context, *ListMyAssetsRequest) (*ListMyAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyAssets not implemented")
}
func (UnimplementedAssetsServiceServer) ListMyAssetLedger(context.Context, *ListMyAssetLedgerRequest) (*ListMyAssetLedgerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyAssetLedger not implemented")
}
func (UnimplementedAssetsServiceServer) mustEmbedUnimplementedAssetsServiceServer() {}
func (UnimplementedAssetsServiceServer) testEmbeddedByValue()                       {}

// UnsafeAssetsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetsServiceServer will
// result in compilation errors.
type UnsafeAssetsServiceServer interface {
	mustEmbedUnimplementedAssetsServiceServer()
}

func RegisterAssetsServiceServer(s grpc.ServiceRegistrar, srv AssetsServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetsService_ServiceDesc, srv)
}

func _AssetsService_ListAssetDefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssetDefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).ListAssetDefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_ListAssetDefs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).ListAssetDefs(ctx, req.(*ListAssetDefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_ListMyAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).ListMyAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_ListMyAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).ListMyAssets(ctx, req.(*ListMyAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_ListMyAssetLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyAssetLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).ListMyAssetLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_ListMyAssetLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).ListMyAssetLedger(ctx, req.(*ListMyAssetLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetsService_ServiceDesc is the grpc.ServiceDesc for AssetsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "torchwood.client.v1.AssetsService",
	HandlerType: (*AssetsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAssetDefs",
			Handler:    _AssetsService_ListAssetDefs_Handler,
		},
		{
			MethodName: "ListMyAssets",
			Handler:    _AssetsService_ListMyAssets_Handler,
		},
		{
			MethodName: "ListMyAssetLedger",
			Handler:    _AssetsService_ListMyAssetLedger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client/v1/assets.proto",
}
