// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: client/v1/databases.proto

package clientv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/torchwooddev/torchwood/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDocumentRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId   string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// 客户端自选 document_id；documents:count 为自定义方法段（REST 自定义动词），
	// 不再占用 document_id 命名空间，可自由取任意合法值。
	DocumentId  string           `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Data        *structpb.Struct `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Permissions []string         `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// 写幂等键（redesign §4.1/§10.1）：作用域 (project, actor, request_id)，
	// 24h 内同键重放返回首次成功响应（响应头 x-torchwood-replayed: true）；
	// 同键不同请求 → IDEMPOTENCY.KEY_CONFLICT。HTTP 面等价 Idempotency-Key 头。
	RequestId     *string `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_client_v1_databases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_databases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_databases_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDocumentRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *CreateDocumentRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *CreateDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreateDocumentRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateDocumentRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CreateDocumentRequest) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

type UpdateDocumentRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId   string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	DocumentId   string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Data         *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Permissions  []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Increment    map[string]int64       `protobuf:"bytes,6,rep,name=increment,proto3" json:"increment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// 用户集合强制 OCC：必须与当前行 _version 相等；未设置 = version_required。
	Version *int64 `protobuf:"varint,7,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// 写幂等键，语义同 CreateDocumentRequest.request_id。
	RequestId     *string `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_client_v1_databases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_databases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_databases_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDocumentRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateDocumentRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UpdateDocumentRequest) GetIncrement() map[string]int64 {
	if x != nil {
		return x.Increment
	}
	return nil
}

func (x *UpdateDocumentRequest) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *UpdateDocumentRequest) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

type UpsertDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId      string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId    string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Data            *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Permissions     []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ConflictColumns []string               `protobuf:"bytes,6,rep,name=conflict_columns,json=conflictColumns,proto3" json:"conflict_columns,omitempty"`
	// 写幂等键，语义同 CreateDocumentRequest.request_id。
	RequestId     *string `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDocumentRequest) Reset() {
	*x = UpsertDocumentRequest{}
	mi := &file_client_v1_databases_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDocumentRequest) ProtoMessage() {}

func (x *UpsertDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_databases_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpsertDocumentRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_databases_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertDocumentRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *UpsertDocumentRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *UpsertDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpsertDocumentRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpsertDocumentRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UpsertDocumentRequest) GetConflictColumns() []string {
	if x != nil {
		return x.ConflictColumns
	}
	return nil
}

func (x *UpsertDocumentRequest) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_client_v1_databases_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_databases_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_databases_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *GetDocumentRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetDocumentRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type DeleteDocumentRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId   string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	DocumentId   string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	// 用户集合强制 OCC：必须与当前行 _version 相等；未设置 = version_required。
	Version *int64 `protobuf:"varint,4,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// 写幂等键，语义同 CreateDocumentRequest.request_id。
	RequestId     *string `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_client_v1_databases_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_databases_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_databases_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDocumentRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *DeleteDocumentRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *DeleteDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DeleteDocumentRequest) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *DeleteDocumentRequest) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

type ListDocumentsRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId   string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// GET 面专用（C7 预决策 3）：page_size/page_token 保留为简单分页参数；
	// 过滤/排序/投影一律走 query（POST :list 的 body 即 Query）。
	PageSize  int32  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	ProjectId string `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Typed AST（唯一过滤载体）。page_size/page_token 与 query 内同名字段
	// 同时设置且不等 → InvalidArgument。
	Query         *v1.Query `protobuf:"bytes,7,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_client_v1_databases_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_databases_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_databases_proto_rawDescGZIP(), []int{5}
}

func (x *ListDocumentsRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *ListDocumentsRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *ListDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListDocumentsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListDocumentsRequest) GetQuery() *v1.Query {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*v1.Document         `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_client_v1_databases_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_databases_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_databases_proto_rawDescGZIP(), []int{6}
}

func (x *ListDocumentsResponse) GetDocuments() []*v1.Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// CountDocumentsRequest 独立于 ListDocumentsRequest（P3-9）：不暴露无效分页参数（page_size/page_token）。
type CountDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Query         *v1.Query              `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	ProjectId     string                 `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountDocumentsRequest) Reset() {
	*x = CountDocumentsRequest{}
	mi := &file_client_v1_databases_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountDocumentsRequest) ProtoMessage() {}

func (x *CountDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_databases_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountDocumentsRequest.ProtoReflect.Descriptor instead.
func (*CountDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_databases_proto_rawDescGZIP(), []int{7}
}

func (x *CountDocumentsRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *CountDocumentsRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *CountDocumentsRequest) GetQuery() *v1.Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *CountDocumentsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type CountDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountDocumentsResponse) Reset() {
	*x = CountDocumentsResponse{}
	mi := &file_client_v1_databases_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountDocumentsResponse) ProtoMessage() {}

func (x *CountDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_databases_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountDocumentsResponse.ProtoReflect.Descriptor instead.
func (*CountDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_databases_proto_rawDescGZIP(), []int{8}
}

func (x *CountDocumentsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ListChangesRequest（阶段④ §4.5）：集合事件补偿查询。
type ListChangesRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId   string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// 续传游标：返回 seq > since_seq 的事件。0 = 从最老可用事件起（缺省）；
	// 早于最老可用事件 → FailedPrecondition EVENTS.RESUME_EXPIRED。
	SinceSeq int64 `protobuf:"varint,3,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	// 单页条数，缺省/上限 500。
	Limit         int32  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	ProjectId     string `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChangesRequest) Reset() {
	*x = ListChangesRequest{}
	mi := &file_client_v1_databases_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangesRequest) ProtoMessage() {}

func (x *ListChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_databases_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangesRequest.ProtoReflect.Descriptor instead.
func (*ListChangesRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_databases_proto_rawDescGZIP(), []int{9}
}

func (x *ListChangesRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *ListChangesRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *ListChangesRequest) GetSinceSeq() int64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *ListChangesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListChangesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListChangesResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Changes []*v1.Change           `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	// 仍有更多可见事件：以 changes 末条 seq 作下一页 since_seq 续传。
	HasMore       bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChangesResponse) Reset() {
	*x = ListChangesResponse{}
	mi := &file_client_v1_databases_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangesResponse) ProtoMessage() {}

func (x *ListChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_databases_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangesResponse.ProtoReflect.Descriptor instead.
func (*ListChangesResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_databases_proto_rawDescGZIP(), []int{10}
}

func (x *ListChangesResponse) GetChanges() []*v1.Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ListChangesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_client_v1_databases_proto protoreflect.FileDescriptor

const file_client_v1_databases_proto_rawDesc = "" +
	"\n" +
	"\x19client/v1/databases.proto\x12\x13torchwood.client.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x15shared/v1/authz.proto\x1a\x16shared/v1/common.proto\x1a\x18shared/v1/document.proto\x1a\x15shared/v1/query.proto\"\x80\x02\n" +
	"\x15CreateDocumentRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12\"\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tH\x00R\trequestId\x88\x01\x01B\r\n" +
	"\v_request_id\"\xc2\x03\n" +
	"\x15UpdateDocumentRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12W\n" +
	"\tincrement\x18\x06 \x03(\v29.torchwood.client.v1.UpdateDocumentRequest.IncrementEntryR\tincrement\x12\x1d\n" +
	"\aversion\x18\a \x01(\x03H\x00R\aversion\x88\x01\x01\x12\"\n" +
	"\n" +
	"request_id\x18\b \x01(\tH\x01R\trequestId\x88\x01\x01\x1a<\n" +
	"\x0eIncrementEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B\n" +
	"\n" +
	"\b_versionB\r\n" +
	"\v_request_id\"\xab\x02\n" +
	"\x15UpsertDocumentRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12)\n" +
	"\x10conflict_columns\x18\x06 \x03(\tR\x0fconflictColumns\x12\"\n" +
	"\n" +
	"request_id\x18\a \x01(\tH\x00R\trequestId\x88\x01\x01B\r\n" +
	"\v_request_id\"\x9a\x01\n" +
	"\x12GetDocumentRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\"\xdc\x01\n" +
	"\x15DeleteDocumentRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\aversion\x18\x04 \x01(\x03H\x00R\aversion\x88\x01\x01\x12\"\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tH\x01R\trequestId\x88\x01\x01B\n" +
	"\n" +
	"\b_versionB\r\n" +
	"\v_request_id\"\xf8\x01\n" +
	"\x14ListDocumentsRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\x120\n" +
	"\x05query\x18\a \x01(\v2\x1a.torchwood.shared.v1.QueryR\x05queryJ\x04\b\x03\x10\x04R\aqueries\"\x8f\x01\n" +
	"\x15ListDocumentsResponse\x12;\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1d.torchwood.shared.v1.DocumentR\tdocuments\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta\"\xbd\x01\n" +
	"\x15CountDocumentsRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x120\n" +
	"\x05query\x18\x04 \x01(\v2\x1a.torchwood.shared.v1.QueryR\x05query\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tR\tprojectIdJ\x04\b\x03\x10\x04R\aqueries\".\n" +
	"\x16CountDocumentsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\xac\x01\n" +
	"\x12ListChangesRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\tsince_seq\x18\x03 \x01(\x03R\bsinceSeq\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tR\tprojectId\"g\n" +
	"\x13ListChangesResponse\x125\n" +
	"\achanges\x18\x01 \x03(\v2\x1b.torchwood.shared.v1.ChangeR\achanges\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore2\xe1\r\n" +
	"\x10DatabasesService\x12\xa9\x01\n" +
	"\x0eCreateDocument\x12*.torchwood.client.v1.CreateDocumentRequest\x1a\x1d.torchwood.shared.v1.Document\"L\x82\xd3\xe4\x93\x02F:\x01*\"A/v1/databases/{database_id}/collections/{collection_id}/documents\x12\xaf\x02\n" +
	"\rListDocuments\x12).torchwood.client.v1.ListDocumentsRequest\x1a*.torchwood.client.v1.ListDocumentsResponse\"\xc6\x01\x92A\"b\x00j\x1e\n" +
	"\x12x-torchwood-access\x12\b\x1a\x06public\x8a\xb2\x19\x02\b\x01\x82\xd3\xe4\x93\x02\x94\x01ZO:\x05query\"F/v1/databases/{database_id}/collections/{collection_id}/documents:list\x12A/v1/databases/{database_id}/collections/{collection_id}/documents\x12\xda\x01\n" +
	"\vGetDocument\x12'.torchwood.client.v1.GetDocumentRequest\x1a\x1d.torchwood.shared.v1.Document\"\x82\x01\x92A\"b\x00j\x1e\n" +
	"\x12x-torchwood-access\x12\b\x1a\x06public\x8a\xb2\x19\x02\b\x01\x82\xd3\xe4\x93\x02Q\x12O/v1/databases/{database_id}/collections/{collection_id}/documents/{document_id}\x12\xb7\x01\n" +
	"\x0eUpdateDocument\x12*.torchwood.client.v1.UpdateDocumentRequest\x1a\x1d.torchwood.shared.v1.Document\"Z\x82\xd3\xe4\x93\x02T:\x01*2O/v1/databases/{database_id}/collections/{collection_id}/documents/{document_id}\x12\xb7\x01\n" +
	"\x0eUpsertDocument\x12*.torchwood.client.v1.UpsertDocumentRequest\x1a\x1d.torchwood.shared.v1.Document\"Z\x82\xd3\xe4\x93\x02T:\x01*\x1aO/v1/databases/{database_id}/collections/{collection_id}/documents/{document_id}\x12\xb1\x01\n" +
	"\x0eDeleteDocument\x12*.torchwood.client.v1.DeleteDocumentRequest\x1a\x1a.torchwood.shared.v1.Empty\"W\x82\xd3\xe4\x93\x02Q*O/v1/databases/{database_id}/collections/{collection_id}/documents/{document_id}\x12\xb5\x02\n" +
	"\x0eCountDocuments\x12*.torchwood.client.v1.CountDocumentsRequest\x1a+.torchwood.client.v1.CountDocumentsResponse\"\xc9\x01\x92A\"b\x00j\x1e\n" +
	"\x12x-torchwood-access\x12\b\x1a\x06public\x8a\xb2\x19\x02\b\x01\x82\xd3\xe4\x93\x02\x97\x01ZL:\x01*\"G/v1/databases/{database_id}/collections/{collection_id}/documents:count\x12G/v1/databases/{database_id}/collections/{collection_id}/documents:count\x12\xa9\x01\n" +
	"\vListChanges\x12'.torchwood.client.v1.ListChangesRequest\x1a(.torchwood.client.v1.ListChangesResponse\"G\x82\xd3\xe4\x93\x02A\x12?/v1/databases/{database_id}/collections/{collection_id}/changes\x1a\x06\x92\xb2\x19\x02\b\x02B\xfa\x03\x92A\xb7\x03RR\n" +
	"\adefault\x12G\n" +
	"\x1dAn unexpected error response.\x12&\n" +
	"$\x1a\".torchwood.shared.v1.ErrorResponseZ\xab\x02\n" +
	"M\n" +
	"\x06Bearer\x12C\b\x02\x12.格式: Bearer <jwt>（Client API 登录态）\x1a\rAuthorization \x02\n" +
	"\x86\x01\n" +
	"\x06apiKey\x12|\b\x02\x12k项目绑定在密钥行上，不需要 X-Torchwood-Project。该头仅 Console admin 会话切换项目。\x1a\tX-API-Key \x02\n" +
	"Q\n" +
	"\x06cookie\x12G\b\x02\x129TORCHWOOD_session_console=<sid>（Console admin 会话）\x1a\x06Cookie \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00z%\n" +
	"\x12x-torchwood-access\x12\x0f\x1a\rauthenticatedZ=github.com/torchwooddev/torchwood/genproto/client/v1;clientv1b\x06proto3"

var (
	file_client_v1_databases_proto_rawDescOnce sync.Once
	file_client_v1_databases_proto_rawDescData []byte
)

func file_client_v1_databases_proto_rawDescGZIP() []byte {
	file_client_v1_databases_proto_rawDescOnce.Do(func() {
		file_client_v1_databases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v1_databases_proto_rawDesc), len(file_client_v1_databases_proto_rawDesc)))
	})
	return file_client_v1_databases_proto_rawDescData
}

var file_client_v1_databases_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_client_v1_databases_proto_goTypes = []any{
	(*CreateDocumentRequest)(nil),  // 0: torchwood.client.v1.CreateDocumentRequest
	(*UpdateDocumentRequest)(nil),  // 1: torchwood.client.v1.UpdateDocumentRequest
	(*UpsertDocumentRequest)(nil),  // 2: torchwood.client.v1.UpsertDocumentRequest
	(*GetDocumentRequest)(nil),     // 3: torchwood.client.v1.GetDocumentRequest
	(*DeleteDocumentRequest)(nil),  // 4: torchwood.client.v1.DeleteDocumentRequest
	(*ListDocumentsRequest)(nil),   // 5: torchwood.client.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),  // 6: torchwood.client.v1.ListDocumentsResponse
	(*CountDocumentsRequest)(nil),  // 7: torchwood.client.v1.CountDocumentsRequest
	(*CountDocumentsResponse)(nil), // 8: torchwood.client.v1.CountDocumentsResponse
	(*ListChangesRequest)(nil),     // 9: torchwood.client.v1.ListChangesRequest
	(*ListChangesResponse)(nil),    // 10: torchwood.client.v1.ListChangesResponse
	nil,                            // 11: torchwood.client.v1.UpdateDocumentRequest.IncrementEntry
	(*structpb.Struct)(nil),        // 12: google.protobuf.Struct
	(*v1.Query)(nil),               // 13: torchwood.shared.v1.Query
	(*v1.Document)(nil),            // 14: torchwood.shared.v1.Document
	(*v1.ListResponseMeta)(nil),    // 15: torchwood.shared.v1.ListResponseMeta
	(*v1.Change)(nil),              // 16: torchwood.shared.v1.Change
	(*v1.Empty)(nil),               // 17: torchwood.shared.v1.Empty
}
var file_client_v1_databases_proto_depIdxs = []int32{
	12, // 0: torchwood.client.v1.CreateDocumentRequest.data:type_name -> google.protobuf.Struct
	12, // 1: torchwood.client.v1.UpdateDocumentRequest.data:type_name -> google.protobuf.Struct
	11, // 2: torchwood.client.v1.UpdateDocumentRequest.increment:type_name -> torchwood.client.v1.UpdateDocumentRequest.IncrementEntry
	12, // 3: torchwood.client.v1.UpsertDocumentRequest.data:type_name -> google.protobuf.Struct
	13, // 4: torchwood.client.v1.ListDocumentsRequest.query:type_name -> torchwood.shared.v1.Query
	14, // 5: torchwood.client.v1.ListDocumentsResponse.documents:type_name -> torchwood.shared.v1.Document
	15, // 6: torchwood.client.v1.ListDocumentsResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	13, // 7: torchwood.client.v1.CountDocumentsRequest.query:type_name -> torchwood.shared.v1.Query
	16, // 8: torchwood.client.v1.ListChangesResponse.changes:type_name -> torchwood.shared.v1.Change
	0,  // 9: torchwood.client.v1.DatabasesService.CreateDocument:input_type -> torchwood.client.v1.CreateDocumentRequest
	5,  // 10: torchwood.client.v1.DatabasesService.ListDocuments:input_type -> torchwood.client.v1.ListDocumentsRequest
	3,  // 11: torchwood.client.v1.DatabasesService.GetDocument:input_type -> torchwood.client.v1.GetDocumentRequest
	1,  // 12: torchwood.client.v1.DatabasesService.UpdateDocument:input_type -> torchwood.client.v1.UpdateDocumentRequest
	2,  // 13: torchwood.client.v1.DatabasesService.UpsertDocument:input_type -> torchwood.client.v1.UpsertDocumentRequest
	4,  // 14: torchwood.client.v1.DatabasesService.DeleteDocument:input_type -> torchwood.client.v1.DeleteDocumentRequest
	7,  // 15: torchwood.client.v1.DatabasesService.CountDocuments:input_type -> torchwood.client.v1.CountDocumentsRequest
	9,  // 16: torchwood.client.v1.DatabasesService.ListChanges:input_type -> torchwood.client.v1.ListChangesRequest
	14, // 17: torchwood.client.v1.DatabasesService.CreateDocument:output_type -> torchwood.shared.v1.Document
	6,  // 18: torchwood.client.v1.DatabasesService.ListDocuments:output_type -> torchwood.client.v1.ListDocumentsResponse
	14, // 19: torchwood.client.v1.DatabasesService.GetDocument:output_type -> torchwood.shared.v1.Document
	14, // 20: torchwood.client.v1.DatabasesService.UpdateDocument:output_type -> torchwood.shared.v1.Document
	14, // 21: torchwood.client.v1.DatabasesService.UpsertDocument:output_type -> torchwood.shared.v1.Document
	17, // 22: torchwood.client.v1.DatabasesService.DeleteDocument:output_type -> torchwood.shared.v1.Empty
	8,  // 23: torchwood.client.v1.DatabasesService.CountDocuments:output_type -> torchwood.client.v1.CountDocumentsResponse
	10, // 24: torchwood.client.v1.DatabasesService.ListChanges:output_type -> torchwood.client.v1.ListChangesResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_client_v1_databases_proto_init() }
func file_client_v1_databases_proto_init() {
	if File_client_v1_databases_proto != nil {
		return
	}
	file_client_v1_databases_proto_msgTypes[0].OneofWrappers = []any{}
	file_client_v1_databases_proto_msgTypes[1].OneofWrappers = []any{}
	file_client_v1_databases_proto_msgTypes[2].OneofWrappers = []any{}
	file_client_v1_databases_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v1_databases_proto_rawDesc), len(file_client_v1_databases_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_v1_databases_proto_goTypes,
		DependencyIndexes: file_client_v1_databases_proto_depIdxs,
		MessageInfos:      file_client_v1_databases_proto_msgTypes,
	}.Build()
	File_client_v1_databases_proto = out.File
	file_client_v1_databases_proto_goTypes = nil
	file_client_v1_databases_proto_depIdxs = nil
}
