// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: client/v1/payments.proto

package clientv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/torchwooddev/torchwood/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentOrder 是支付订单（v3 设计 §1.3）。amount 一律最小货币单位的
// int64（禁止 float）；status 状态机：
// created → paying → paid | failed | closed → refunding → refunded。
type PaymentOrder struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Amount   int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	// topup | item_purchase | subscription
	PurposeKind string `protobuf:"bytes,5,opt,name=purpose_kind,json=purposeKind,proto3" json:"purpose_kind,omitempty"`
	// 用途载荷：{currency_code, amount} / {asset_code, quantity} / {plan_code}
	Purpose        *structpb.Struct       `protobuf:"bytes,6,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PaidAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// 渠道收银台地址（Stripe Checkout URL 等）；仅 CreateOrder 响应填充，
	// 查询接口不返回。
	PaymentUrl    string `protobuf:"bytes,12,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentOrder) Reset() {
	*x = PaymentOrder{}
	mi := &file_client_v1_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentOrder) ProtoMessage() {}

func (x *PaymentOrder) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentOrder.ProtoReflect.Descriptor instead.
func (*PaymentOrder) Descriptor() ([]byte, []int) {
	return file_client_v1_payments_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentOrder) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PaymentOrder) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentOrder) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentOrder) GetPurposeKind() string {
	if x != nil {
		return x.PurposeKind
	}
	return ""
}

func (x *PaymentOrder) GetPurpose() *structpb.Struct {
	if x != nil {
		return x.Purpose
	}
	return nil
}

func (x *PaymentOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentOrder) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PaymentOrder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentOrder) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *PaymentOrder) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PaymentOrder) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type CreateOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端建单幂等键：同 (project, key) 重复建单返回原单（设计 §1.3）。
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// stripe | wechat | alipay | ios_iap。
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// 最小货币单位金额，必须 > 0（如 1999 = 19.99 USD）。
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// ISO-4217 三字母码（usd / cny ...）。
	Currency string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	// topup | item_purchase（subscription 在 PR3 开放）。
	PurposeKind string           `protobuf:"bytes,5,opt,name=purpose_kind,json=purposeKind,proto3" json:"purpose_kind,omitempty"`
	Purpose     *structpb.Struct `protobuf:"bytes,6,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// Checkout 回跳地址（Stripe 一次性支付）；未传则用 server.http.public_url。
	SuccessUrl    *string `protobuf:"bytes,7,opt,name=success_url,json=successUrl,proto3,oneof" json:"success_url,omitempty"`
	CancelUrl     *string `protobuf:"bytes,8,opt,name=cancel_url,json=cancelUrl,proto3,oneof" json:"cancel_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_client_v1_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_payments_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateOrderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateOrderRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderRequest) GetPurposeKind() string {
	if x != nil {
		return x.PurposeKind
	}
	return ""
}

func (x *CreateOrderRequest) GetPurpose() *structpb.Struct {
	if x != nil {
		return x.Purpose
	}
	return nil
}

func (x *CreateOrderRequest) GetSuccessUrl() string {
	if x != nil && x.SuccessUrl != nil {
		return *x.SuccessUrl
	}
	return ""
}

func (x *CreateOrderRequest) GetCancelUrl() string {
	if x != nil && x.CancelUrl != nil {
		return *x.CancelUrl
	}
	return ""
}

type CreateOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Order *PaymentOrder          `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	// true = 命中幂等键返回原单（未向渠道重复下单）。
	IdempotentReplay bool `protobuf:"varint,2,opt,name=idempotent_replay,json=idempotentReplay,proto3" json:"idempotent_replay,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_client_v1_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_payments_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetOrder() *PaymentOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderResponse) GetIdempotentReplay() bool {
	if x != nil {
		return x.IdempotentReplay
	}
	return false
}

type GetMyOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyOrderRequest) Reset() {
	*x = GetMyOrderRequest{}
	mi := &file_client_v1_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyOrderRequest) ProtoMessage() {}

func (x *GetMyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyOrderRequest.ProtoReflect.Descriptor instead.
func (*GetMyOrderRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_payments_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListMyOrdersRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PageSize int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 不透明游标（上一页最后一条的创建时间）。
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrdersRequest) Reset() {
	*x = ListMyOrdersRequest{}
	mi := &file_client_v1_payments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrdersRequest) ProtoMessage() {}

func (x *ListMyOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_payments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListMyOrdersRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_payments_proto_rawDescGZIP(), []int{4}
}

func (x *ListMyOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMyOrdersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListMyOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*PaymentOrder        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrdersResponse) Reset() {
	*x = ListMyOrdersResponse{}
	mi := &file_client_v1_payments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrdersResponse) ProtoMessage() {}

func (x *ListMyOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_payments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListMyOrdersResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_payments_proto_rawDescGZIP(), []int{5}
}

func (x *ListMyOrdersResponse) GetOrders() []*PaymentOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListMyOrdersResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// VerifyReceiptRequest 是 iOS 验票请求：receipt 为 StoreKit base64 PKCS7
// 或 StoreKit 2 signed transaction JWS；order_id 指向本人 ios_iap 订单。
type VerifyReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Receipt       string                 `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyReceiptRequest) Reset() {
	*x = VerifyReceiptRequest{}
	mi := &file_client_v1_payments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyReceiptRequest) ProtoMessage() {}

func (x *VerifyReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_payments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyReceiptRequest.ProtoReflect.Descriptor instead.
func (*VerifyReceiptRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_payments_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyReceiptRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *VerifyReceiptRequest) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

type VerifyReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *PaymentOrder          `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// true = 同 transactionId 重放（已履约，不重复发货）。
	IdempotentReplay bool `protobuf:"varint,3,opt,name=idempotent_replay,json=idempotentReplay,proto3" json:"idempotent_replay,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyReceiptResponse) Reset() {
	*x = VerifyReceiptResponse{}
	mi := &file_client_v1_payments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyReceiptResponse) ProtoMessage() {}

func (x *VerifyReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_payments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyReceiptResponse.ProtoReflect.Descriptor instead.
func (*VerifyReceiptResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_payments_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyReceiptResponse) GetOrder() *PaymentOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *VerifyReceiptResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VerifyReceiptResponse) GetIdempotentReplay() bool {
	if x != nil {
		return x.IdempotentReplay
	}
	return false
}

var File_client_v1_payments_proto protoreflect.FileDescriptor

const file_client_v1_payments_proto_rawDesc = "" +
	"\n" +
	"\x18client/v1/payments.proto\x12\x13torchwood.client.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x15shared/v1/authz.proto\x1a\x16shared/v1/common.proto\"\xd1\x03\n" +
	"\fPaymentOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12!\n" +
	"\fpurpose_kind\x18\x05 \x01(\tR\vpurposeKind\x121\n" +
	"\apurpose\x18\x06 \x01(\v2\x17.google.protobuf.StructR\apurpose\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\apaid_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1f\n" +
	"\vpayment_url\x18\f \x01(\tR\n" +
	"paymentUrl\"\xcc\x02\n" +
	"\x12CreateOrderRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12!\n" +
	"\fpurpose_kind\x18\x05 \x01(\tR\vpurposeKind\x121\n" +
	"\apurpose\x18\x06 \x01(\v2\x17.google.protobuf.StructR\apurpose\x12$\n" +
	"\vsuccess_url\x18\a \x01(\tH\x00R\n" +
	"successUrl\x88\x01\x01\x12\"\n" +
	"\n" +
	"cancel_url\x18\b \x01(\tH\x01R\tcancelUrl\x88\x01\x01B\x0e\n" +
	"\f_success_urlB\r\n" +
	"\v_cancel_url\"{\n" +
	"\x13CreateOrderResponse\x127\n" +
	"\x05order\x18\x01 \x01(\v2!.torchwood.client.v1.PaymentOrderR\x05order\x12+\n" +
	"\x11idempotent_replay\x18\x02 \x01(\bR\x10idempotentReplay\".\n" +
	"\x11GetMyOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"Q\n" +
	"\x13ListMyOrdersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x8c\x01\n" +
	"\x14ListMyOrdersResponse\x129\n" +
	"\x06orders\x18\x01 \x03(\v2!.torchwood.client.v1.PaymentOrderR\x06orders\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta\"K\n" +
	"\x14VerifyReceiptRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x18\n" +
	"\areceipt\x18\x02 \x01(\tR\areceipt\"\xa4\x01\n" +
	"\x15VerifyReceiptResponse\x127\n" +
	"\x05order\x18\x01 \x01(\v2!.torchwood.client.v1.PaymentOrderR\x05order\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12+\n" +
	"\x11idempotent_replay\x18\x03 \x01(\bR\x10idempotentReplay2\xb5\x04\n" +
	"\x0fPaymentsService\x12\x80\x01\n" +
	"\vCreateOrder\x12'.torchwood.client.v1.CreateOrderRequest\x1a(.torchwood.client.v1.CreateOrderResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/payments/orders\x12\x7f\n" +
	"\n" +
	"GetMyOrder\x12&.torchwood.client.v1.GetMyOrderRequest\x1a!.torchwood.client.v1.PaymentOrder\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/payments/orders/{order_id}\x12\x80\x01\n" +
	"\fListMyOrders\x12(.torchwood.client.v1.ListMyOrdersRequest\x1a).torchwood.client.v1.ListMyOrdersResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/payments/orders\x12\x92\x01\n" +
	"\rVerifyReceipt\x12).torchwood.client.v1.VerifyReceiptRequest\x1a*.torchwood.client.v1.VerifyReceiptResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/payments/ios/verify-receipt\x1a\x06\x92\xb2\x19\x02\b\x02B\xa6\x03\x92A\xe3\x02Z\xab\x02\n" +
	"M\n" +
	"\x06Bearer\x12C\b\x02\x12.格式: Bearer <jwt>（Client API 登录态）\x1a\rAuthorization \x02\n" +
	"\x86\x01\n" +
	"\x06apiKey\x12|\b\x02\x12k项目绑定在密钥行上，不需要 X-Torchwood-Project。该头仅 Console admin 会话切换项目。\x1a\tX-API-Key \x02\n" +
	"Q\n" +
	"\x06cookie\x12G\b\x02\x129TORCHWOOD_session_console=<sid>（Console admin 会话）\x1a\x06Cookie \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00z%\n" +
	"\x12x-torchwood-access\x12\x0f\x1a\rauthenticatedZ=github.com/torchwooddev/torchwood/genproto/client/v1;clientv1b\x06proto3"

var (
	file_client_v1_payments_proto_rawDescOnce sync.Once
	file_client_v1_payments_proto_rawDescData []byte
)

func file_client_v1_payments_proto_rawDescGZIP() []byte {
	file_client_v1_payments_proto_rawDescOnce.Do(func() {
		file_client_v1_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v1_payments_proto_rawDesc), len(file_client_v1_payments_proto_rawDesc)))
	})
	return file_client_v1_payments_proto_rawDescData
}

var file_client_v1_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_client_v1_payments_proto_goTypes = []any{
	(*PaymentOrder)(nil),          // 0: torchwood.client.v1.PaymentOrder
	(*CreateOrderRequest)(nil),    // 1: torchwood.client.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),   // 2: torchwood.client.v1.CreateOrderResponse
	(*GetMyOrderRequest)(nil),     // 3: torchwood.client.v1.GetMyOrderRequest
	(*ListMyOrdersRequest)(nil),   // 4: torchwood.client.v1.ListMyOrdersRequest
	(*ListMyOrdersResponse)(nil),  // 5: torchwood.client.v1.ListMyOrdersResponse
	(*VerifyReceiptRequest)(nil),  // 6: torchwood.client.v1.VerifyReceiptRequest
	(*VerifyReceiptResponse)(nil), // 7: torchwood.client.v1.VerifyReceiptResponse
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*v1.ListResponseMeta)(nil),   // 10: torchwood.shared.v1.ListResponseMeta
}
var file_client_v1_payments_proto_depIdxs = []int32{
	8,  // 0: torchwood.client.v1.PaymentOrder.purpose:type_name -> google.protobuf.Struct
	9,  // 1: torchwood.client.v1.PaymentOrder.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: torchwood.client.v1.PaymentOrder.paid_at:type_name -> google.protobuf.Timestamp
	9,  // 3: torchwood.client.v1.PaymentOrder.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 4: torchwood.client.v1.CreateOrderRequest.purpose:type_name -> google.protobuf.Struct
	0,  // 5: torchwood.client.v1.CreateOrderResponse.order:type_name -> torchwood.client.v1.PaymentOrder
	0,  // 6: torchwood.client.v1.ListMyOrdersResponse.orders:type_name -> torchwood.client.v1.PaymentOrder
	10, // 7: torchwood.client.v1.ListMyOrdersResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	0,  // 8: torchwood.client.v1.VerifyReceiptResponse.order:type_name -> torchwood.client.v1.PaymentOrder
	1,  // 9: torchwood.client.v1.PaymentsService.CreateOrder:input_type -> torchwood.client.v1.CreateOrderRequest
	3,  // 10: torchwood.client.v1.PaymentsService.GetMyOrder:input_type -> torchwood.client.v1.GetMyOrderRequest
	4,  // 11: torchwood.client.v1.PaymentsService.ListMyOrders:input_type -> torchwood.client.v1.ListMyOrdersRequest
	6,  // 12: torchwood.client.v1.PaymentsService.VerifyReceipt:input_type -> torchwood.client.v1.VerifyReceiptRequest
	2,  // 13: torchwood.client.v1.PaymentsService.CreateOrder:output_type -> torchwood.client.v1.CreateOrderResponse
	0,  // 14: torchwood.client.v1.PaymentsService.GetMyOrder:output_type -> torchwood.client.v1.PaymentOrder
	5,  // 15: torchwood.client.v1.PaymentsService.ListMyOrders:output_type -> torchwood.client.v1.ListMyOrdersResponse
	7,  // 16: torchwood.client.v1.PaymentsService.VerifyReceipt:output_type -> torchwood.client.v1.VerifyReceiptResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_client_v1_payments_proto_init() }
func file_client_v1_payments_proto_init() {
	if File_client_v1_payments_proto != nil {
		return
	}
	file_client_v1_payments_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v1_payments_proto_rawDesc), len(file_client_v1_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_v1_payments_proto_goTypes,
		DependencyIndexes: file_client_v1_payments_proto_depIdxs,
		MessageInfos:      file_client_v1_payments_proto_msgTypes,
	}.Build()
	File_client_v1_payments_proto = out.File
	file_client_v1_payments_proto_goTypes = nil
	file_client_v1_payments_proto_depIdxs = nil
}
